// Code generated by go-swagger; DO NOT EDIT.

package cognitive_profile_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReadCognitiveProfileParams creates a new ReadCognitiveProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReadCognitiveProfileParams() *ReadCognitiveProfileParams {
	return &ReadCognitiveProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReadCognitiveProfileParamsWithTimeout creates a new ReadCognitiveProfileParams object
// with the ability to set a timeout on a request.
func NewReadCognitiveProfileParamsWithTimeout(timeout time.Duration) *ReadCognitiveProfileParams {
	return &ReadCognitiveProfileParams{
		timeout: timeout,
	}
}

// NewReadCognitiveProfileParamsWithContext creates a new ReadCognitiveProfileParams object
// with the ability to set a context for a request.
func NewReadCognitiveProfileParamsWithContext(ctx context.Context) *ReadCognitiveProfileParams {
	return &ReadCognitiveProfileParams{
		Context: ctx,
	}
}

// NewReadCognitiveProfileParamsWithHTTPClient creates a new ReadCognitiveProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewReadCognitiveProfileParamsWithHTTPClient(client *http.Client) *ReadCognitiveProfileParams {
	return &ReadCognitiveProfileParams{
		HTTPClient: client,
	}
}

/*
ReadCognitiveProfileParams contains all the parameters to send to the API endpoint

	for the read cognitive profile operation.

	Typically these are written to a http.Request.
*/
type ReadCognitiveProfileParams struct {

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the read cognitive profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadCognitiveProfileParams) WithDefaults() *ReadCognitiveProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the read cognitive profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReadCognitiveProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the read cognitive profile params
func (o *ReadCognitiveProfileParams) WithTimeout(timeout time.Duration) *ReadCognitiveProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read cognitive profile params
func (o *ReadCognitiveProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read cognitive profile params
func (o *ReadCognitiveProfileParams) WithContext(ctx context.Context) *ReadCognitiveProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read cognitive profile params
func (o *ReadCognitiveProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read cognitive profile params
func (o *ReadCognitiveProfileParams) WithHTTPClient(client *http.Client) *ReadCognitiveProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read cognitive profile params
func (o *ReadCognitiveProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the read cognitive profile params
func (o *ReadCognitiveProfileParams) WithID(id string) *ReadCognitiveProfileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the read cognitive profile params
func (o *ReadCognitiveProfileParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReadCognitiveProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
