// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// UpdateCatalog2Reader is a Reader for the UpdateCatalog2 structure.
type UpdateCatalog2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateCatalog2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateCatalog2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateCatalog2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateCatalog2OK creates a UpdateCatalog2OK with default headers values
func NewUpdateCatalog2OK() *UpdateCatalog2OK {
	return &UpdateCatalog2OK{}
}

/*
UpdateCatalog2OK describes a response with status code 200, with default header values.

A successful response.
*/
type UpdateCatalog2OK struct {
	Payload *models.CasesCatalog
}

// IsSuccess returns true when this update catalog2 Ok response has a 2xx status code
func (o *UpdateCatalog2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update catalog2 Ok response has a 3xx status code
func (o *UpdateCatalog2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update catalog2 Ok response has a 4xx status code
func (o *UpdateCatalog2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update catalog2 Ok response has a 5xx status code
func (o *UpdateCatalog2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this update catalog2 Ok response a status code equal to that given
func (o *UpdateCatalog2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update catalog2 Ok response
func (o *UpdateCatalog2OK) Code() int {
	return 200
}

func (o *UpdateCatalog2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /cases/catalogs/{id}][%d] updateCatalog2Ok %s", 200, payload)
}

func (o *UpdateCatalog2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /cases/catalogs/{id}][%d] updateCatalog2Ok %s", 200, payload)
}

func (o *UpdateCatalog2OK) GetPayload() *models.CasesCatalog {
	return o.Payload
}

func (o *UpdateCatalog2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CasesCatalog)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCatalog2Default creates a UpdateCatalog2Default with default headers values
func NewUpdateCatalog2Default(code int) *UpdateCatalog2Default {
	return &UpdateCatalog2Default{
		_statusCode: code,
	}
}

/*
UpdateCatalog2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UpdateCatalog2Default struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this update catalog2 default response has a 2xx status code
func (o *UpdateCatalog2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update catalog2 default response has a 3xx status code
func (o *UpdateCatalog2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update catalog2 default response has a 4xx status code
func (o *UpdateCatalog2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update catalog2 default response has a 5xx status code
func (o *UpdateCatalog2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update catalog2 default response a status code equal to that given
func (o *UpdateCatalog2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update catalog2 default response
func (o *UpdateCatalog2Default) Code() int {
	return o._statusCode
}

func (o *UpdateCatalog2Default) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /cases/catalogs/{id}][%d] UpdateCatalog2 default %s", o._statusCode, payload)
}

func (o *UpdateCatalog2Default) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /cases/catalogs/{id}][%d] UpdateCatalog2 default %s", o._statusCode, payload)
}

func (o *UpdateCatalog2Default) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *UpdateCatalog2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
