// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// CustomersLicenseUsersReader is a Reader for the CustomersLicenseUsers structure.
type CustomersLicenseUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomersLicenseUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomersLicenseUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /products/{id}/users] Customers_LicenseUsers", response, response.Code())
	}
}

// NewCustomersLicenseUsersOK creates a CustomersLicenseUsersOK with default headers values
func NewCustomersLicenseUsersOK() *CustomersLicenseUsersOK {
	return &CustomersLicenseUsersOK{}
}

/*
CustomersLicenseUsersOK describes a response with status code 200, with default header values.

A successful response.
*/
type CustomersLicenseUsersOK struct {
	Payload *models.APILicenseUsersResponse
}

// IsSuccess returns true when this customers license users Ok response has a 2xx status code
func (o *CustomersLicenseUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customers license users Ok response has a 3xx status code
func (o *CustomersLicenseUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customers license users Ok response has a 4xx status code
func (o *CustomersLicenseUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customers license users Ok response has a 5xx status code
func (o *CustomersLicenseUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customers license users Ok response a status code equal to that given
func (o *CustomersLicenseUsersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customers license users Ok response
func (o *CustomersLicenseUsersOK) Code() int {
	return 200
}

func (o *CustomersLicenseUsersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{id}/users][%d] customersLicenseUsersOk %s", 200, payload)
}

func (o *CustomersLicenseUsersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products/{id}/users][%d] customersLicenseUsersOk %s", 200, payload)
}

func (o *CustomersLicenseUsersOK) GetPayload() *models.APILicenseUsersResponse {
	return o.Payload
}

func (o *CustomersLicenseUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APILicenseUsersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
