// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// ExtensionsSearchTypeReader is a Reader for the ExtensionsSearchType structure.
type ExtensionsSearchTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtensionsSearchTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtensionsSearchTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /types/extensions] Extensions_SearchType", response, response.Code())
	}
}

// NewExtensionsSearchTypeOK creates a ExtensionsSearchTypeOK with default headers values
func NewExtensionsSearchTypeOK() *ExtensionsSearchTypeOK {
	return &ExtensionsSearchTypeOK{}
}

/*
ExtensionsSearchTypeOK describes a response with status code 200, with default header values.

A successful response.
*/
type ExtensionsSearchTypeOK struct {
	Payload *models.WebitelProtoDataExtensionList
}

// IsSuccess returns true when this extensions search type Ok response has a 2xx status code
func (o *ExtensionsSearchTypeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extensions search type Ok response has a 3xx status code
func (o *ExtensionsSearchTypeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extensions search type Ok response has a 4xx status code
func (o *ExtensionsSearchTypeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extensions search type Ok response has a 5xx status code
func (o *ExtensionsSearchTypeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extensions search type Ok response a status code equal to that given
func (o *ExtensionsSearchTypeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the extensions search type Ok response
func (o *ExtensionsSearchTypeOK) Code() int {
	return 200
}

func (o *ExtensionsSearchTypeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /types/extensions][%d] extensionsSearchTypeOk %s", 200, payload)
}

func (o *ExtensionsSearchTypeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /types/extensions][%d] extensionsSearchTypeOk %s", 200, payload)
}

func (o *ExtensionsSearchTypeOK) GetPayload() *models.WebitelProtoDataExtensionList {
	return o.Payload
}

func (o *ExtensionsSearchTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebitelProtoDataExtensionList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
