// Code generated by go-swagger; DO NOT EDIT.

package extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewExtensionsLocateParams creates a new ExtensionsLocateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtensionsLocateParams() *ExtensionsLocateParams {
	return &ExtensionsLocateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExtensionsLocateParamsWithTimeout creates a new ExtensionsLocateParams object
// with the ability to set a timeout on a request.
func NewExtensionsLocateParamsWithTimeout(timeout time.Duration) *ExtensionsLocateParams {
	return &ExtensionsLocateParams{
		timeout: timeout,
	}
}

// NewExtensionsLocateParamsWithContext creates a new ExtensionsLocateParams object
// with the ability to set a context for a request.
func NewExtensionsLocateParamsWithContext(ctx context.Context) *ExtensionsLocateParams {
	return &ExtensionsLocateParams{
		Context: ctx,
	}
}

// NewExtensionsLocateParamsWithHTTPClient creates a new ExtensionsLocateParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtensionsLocateParamsWithHTTPClient(client *http.Client) *ExtensionsLocateParams {
	return &ExtensionsLocateParams{
		HTTPClient: client,
	}
}

/*
ExtensionsLocateParams contains all the parameters to send to the API endpoint

	for the extensions locate operation.

	Typically these are written to a http.Request.
*/
type ExtensionsLocateParams struct {

	/* Fields.

	     Fields [Q]uery to build result dataset record.
	```
	fields ::= field [ *( "," field ) ]
	field  ::= name [ *( func ) ] [ inner ]
	inner  ::= "{" fields "}"
	funcs  ::= *( func )
	func   ::= "." name "(" [ args ] ")"
	name   ::= ALPHA / DIGIT / USCORE

	ALPHA    = %x41-5A / %x61-7A  ; "A"-"Z" / "a"-"z"
	DIGIT    = %x30-39            ; "0"-"9"
	USCORE   = %x5F ; underscore  ; "_"
	```
	*/
	Fields []string

	/* ID.

	   [`record.id`]
	*/
	ID string

	/* Repo.

	   [`types.repo`]
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the extensions locate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtensionsLocateParams) WithDefaults() *ExtensionsLocateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extensions locate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtensionsLocateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extensions locate params
func (o *ExtensionsLocateParams) WithTimeout(timeout time.Duration) *ExtensionsLocateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extensions locate params
func (o *ExtensionsLocateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the extensions locate params
func (o *ExtensionsLocateParams) WithContext(ctx context.Context) *ExtensionsLocateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extensions locate params
func (o *ExtensionsLocateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the extensions locate params
func (o *ExtensionsLocateParams) WithHTTPClient(client *http.Client) *ExtensionsLocateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extensions locate params
func (o *ExtensionsLocateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the extensions locate params
func (o *ExtensionsLocateParams) WithFields(fields []string) *ExtensionsLocateParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the extensions locate params
func (o *ExtensionsLocateParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithID adds the id to the extensions locate params
func (o *ExtensionsLocateParams) WithID(id string) *ExtensionsLocateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the extensions locate params
func (o *ExtensionsLocateParams) SetID(id string) {
	o.ID = id
}

// WithRepo adds the repo to the extensions locate params
func (o *ExtensionsLocateParams) WithRepo(repo string) *ExtensionsLocateParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the extensions locate params
func (o *ExtensionsLocateParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *ExtensionsLocateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamExtensionsLocate binds the parameter fields
func (o *ExtensionsLocateParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldsIS := swag.JoinByFormat(fieldsIC, "multi")

	return fieldsIS
}
