// Code generated by go-swagger; DO NOT EDIT.

package preset_query_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// DeletePresetQueryReader is a Reader for the DeletePresetQuery structure.
type DeletePresetQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePresetQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePresetQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePresetQueryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePresetQueryOK creates a DeletePresetQueryOK with default headers values
func NewDeletePresetQueryOK() *DeletePresetQueryOK {
	return &DeletePresetQueryOK{}
}

/*
DeletePresetQueryOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeletePresetQueryOK struct {
	Payload *models.EnginePresetQuery
}

// IsSuccess returns true when this delete preset query Ok response has a 2xx status code
func (o *DeletePresetQueryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete preset query Ok response has a 3xx status code
func (o *DeletePresetQueryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete preset query Ok response has a 4xx status code
func (o *DeletePresetQueryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete preset query Ok response has a 5xx status code
func (o *DeletePresetQueryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete preset query Ok response a status code equal to that given
func (o *DeletePresetQueryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete preset query Ok response
func (o *DeletePresetQueryOK) Code() int {
	return 200
}

func (o *DeletePresetQueryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /call_center/preset/query/{id}][%d] deletePresetQueryOk %s", 200, payload)
}

func (o *DeletePresetQueryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /call_center/preset/query/{id}][%d] deletePresetQueryOk %s", 200, payload)
}

func (o *DeletePresetQueryOK) GetPayload() *models.EnginePresetQuery {
	return o.Payload
}

func (o *DeletePresetQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnginePresetQuery)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePresetQueryDefault creates a DeletePresetQueryDefault with default headers values
func NewDeletePresetQueryDefault(code int) *DeletePresetQueryDefault {
	return &DeletePresetQueryDefault{
		_statusCode: code,
	}
}

/*
DeletePresetQueryDefault describes a response with status code -1, with default header values.

Server error
*/
type DeletePresetQueryDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this delete preset query default response has a 2xx status code
func (o *DeletePresetQueryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete preset query default response has a 3xx status code
func (o *DeletePresetQueryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete preset query default response has a 4xx status code
func (o *DeletePresetQueryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete preset query default response has a 5xx status code
func (o *DeletePresetQueryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete preset query default response a status code equal to that given
func (o *DeletePresetQueryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete preset query default response
func (o *DeletePresetQueryDefault) Code() int {
	return o._statusCode
}

func (o *DeletePresetQueryDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /call_center/preset/query/{id}][%d] DeletePresetQuery default %s", o._statusCode, payload)
}

func (o *DeletePresetQueryDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /call_center/preset/query/{id}][%d] DeletePresetQuery default %s", o._statusCode, payload)
}

func (o *DeletePresetQueryDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *DeletePresetQueryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
