// Code generated by go-swagger; DO NOT EDIT.

package emails

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// EmailsUpdateEmailReader is a Reader for the EmailsUpdateEmail structure.
type EmailsUpdateEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmailsUpdateEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEmailsUpdateEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /contacts/{contact_id}/emails/{etag}] Emails_UpdateEmail", response, response.Code())
	}
}

// NewEmailsUpdateEmailOK creates a EmailsUpdateEmailOK with default headers values
func NewEmailsUpdateEmailOK() *EmailsUpdateEmailOK {
	return &EmailsUpdateEmailOK{}
}

/*
EmailsUpdateEmailOK describes a response with status code 200, with default header values.

A successful response.
*/
type EmailsUpdateEmailOK struct {
	Payload *models.WebitelContactsEmailList
}

// IsSuccess returns true when this emails update email Ok response has a 2xx status code
func (o *EmailsUpdateEmailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this emails update email Ok response has a 3xx status code
func (o *EmailsUpdateEmailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this emails update email Ok response has a 4xx status code
func (o *EmailsUpdateEmailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this emails update email Ok response has a 5xx status code
func (o *EmailsUpdateEmailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this emails update email Ok response a status code equal to that given
func (o *EmailsUpdateEmailOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the emails update email Ok response
func (o *EmailsUpdateEmailOK) Code() int {
	return 200
}

func (o *EmailsUpdateEmailOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /contacts/{contact_id}/emails/{etag}][%d] emailsUpdateEmailOk %s", 200, payload)
}

func (o *EmailsUpdateEmailOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /contacts/{contact_id}/emails/{etag}][%d] emailsUpdateEmailOk %s", 200, payload)
}

func (o *EmailsUpdateEmailOK) GetPayload() *models.WebitelContactsEmailList {
	return o.Payload
}

func (o *EmailsUpdateEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebitelContactsEmailList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
