// Code generated by go-swagger; DO NOT EDIT.

package ldap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// LDAPSearchLDAProcessReader is a Reader for the LDAPSearchLDAProcess structure.
type LDAPSearchLDAProcessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LDAPSearchLDAProcessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLDAPSearchLDAProcessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ldap/{catalog_id}/rsync] LDAP_SearchLDAProcess", response, response.Code())
	}
}

// NewLDAPSearchLDAProcessOK creates a LDAPSearchLDAProcessOK with default headers values
func NewLDAPSearchLDAProcessOK() *LDAPSearchLDAProcessOK {
	return &LDAPSearchLDAProcessOK{}
}

/*
LDAPSearchLDAProcessOK describes a response with status code 200, with default header values.

A successful response.
*/
type LDAPSearchLDAProcessOK struct {
	Payload *models.APILDAProcessResponse
}

// IsSuccess returns true when this ldap search l d a process Ok response has a 2xx status code
func (o *LDAPSearchLDAProcessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ldap search l d a process Ok response has a 3xx status code
func (o *LDAPSearchLDAProcessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ldap search l d a process Ok response has a 4xx status code
func (o *LDAPSearchLDAProcessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ldap search l d a process Ok response has a 5xx status code
func (o *LDAPSearchLDAProcessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ldap search l d a process Ok response a status code equal to that given
func (o *LDAPSearchLDAProcessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ldap search l d a process Ok response
func (o *LDAPSearchLDAProcessOK) Code() int {
	return 200
}

func (o *LDAPSearchLDAProcessOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ldap/{catalog_id}/rsync][%d] ldapSearchLDAProcessOk %s", 200, payload)
}

func (o *LDAPSearchLDAProcessOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ldap/{catalog_id}/rsync][%d] ldapSearchLDAProcessOk %s", 200, payload)
}

func (o *LDAPSearchLDAProcessOK) GetPayload() *models.APILDAProcessResponse {
	return o.Payload
}

func (o *LDAPSearchLDAProcessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APILDAProcessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
