// Code generated by go-swagger; DO NOT EDIT.

package ldap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewLDAPResyncLDAPCatalogParams creates a new LDAPResyncLDAPCatalogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLDAPResyncLDAPCatalogParams() *LDAPResyncLDAPCatalogParams {
	return &LDAPResyncLDAPCatalogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLDAPResyncLDAPCatalogParamsWithTimeout creates a new LDAPResyncLDAPCatalogParams object
// with the ability to set a timeout on a request.
func NewLDAPResyncLDAPCatalogParamsWithTimeout(timeout time.Duration) *LDAPResyncLDAPCatalogParams {
	return &LDAPResyncLDAPCatalogParams{
		timeout: timeout,
	}
}

// NewLDAPResyncLDAPCatalogParamsWithContext creates a new LDAPResyncLDAPCatalogParams object
// with the ability to set a context for a request.
func NewLDAPResyncLDAPCatalogParamsWithContext(ctx context.Context) *LDAPResyncLDAPCatalogParams {
	return &LDAPResyncLDAPCatalogParams{
		Context: ctx,
	}
}

// NewLDAPResyncLDAPCatalogParamsWithHTTPClient creates a new LDAPResyncLDAPCatalogParams object
// with the ability to set a custom HTTPClient for a request.
func NewLDAPResyncLDAPCatalogParamsWithHTTPClient(client *http.Client) *LDAPResyncLDAPCatalogParams {
	return &LDAPResyncLDAPCatalogParams{
		HTTPClient: client,
	}
}

/*
LDAPResyncLDAPCatalogParams contains all the parameters to send to the API endpoint

	for the LDAP resync LDAP catalog operation.

	Typically these are written to a http.Request.
*/
type LDAPResyncLDAPCatalogParams struct {

	// Body.
	Body *models.APILDAPResyncLDAPCatalogBody

	/* CatalogID.

	     LDAP Catalog unique IDentifier to sync with

	catalog_id

	     Format: int64
	*/
	CatalogID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the LDAP resync LDAP catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LDAPResyncLDAPCatalogParams) WithDefaults() *LDAPResyncLDAPCatalogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the LDAP resync LDAP catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LDAPResyncLDAPCatalogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) WithTimeout(timeout time.Duration) *LDAPResyncLDAPCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) WithContext(ctx context.Context) *LDAPResyncLDAPCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) WithHTTPClient(client *http.Client) *LDAPResyncLDAPCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) WithBody(body *models.APILDAPResyncLDAPCatalogBody) *LDAPResyncLDAPCatalogParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) SetBody(body *models.APILDAPResyncLDAPCatalogBody) {
	o.Body = body
}

// WithCatalogID adds the catalogID to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) WithCatalogID(catalogID string) *LDAPResyncLDAPCatalogParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the LDAP resync LDAP catalog params
func (o *LDAPResyncLDAPCatalogParams) SetCatalogID(catalogID string) {
	o.CatalogID = catalogID
}

// WriteToRequest writes these params to a swagger request
func (o *LDAPResyncLDAPCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param catalog_id
	if err := r.SetPathParam("catalog_id", o.CatalogID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
