// Code generated by go-swagger; DO NOT EDIT.

package file_policies_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewFilePolicyApplyParams creates a new FilePolicyApplyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFilePolicyApplyParams() *FilePolicyApplyParams {
	return &FilePolicyApplyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFilePolicyApplyParamsWithTimeout creates a new FilePolicyApplyParams object
// with the ability to set a timeout on a request.
func NewFilePolicyApplyParamsWithTimeout(timeout time.Duration) *FilePolicyApplyParams {
	return &FilePolicyApplyParams{
		timeout: timeout,
	}
}

// NewFilePolicyApplyParamsWithContext creates a new FilePolicyApplyParams object
// with the ability to set a context for a request.
func NewFilePolicyApplyParamsWithContext(ctx context.Context) *FilePolicyApplyParams {
	return &FilePolicyApplyParams{
		Context: ctx,
	}
}

// NewFilePolicyApplyParamsWithHTTPClient creates a new FilePolicyApplyParams object
// with the ability to set a custom HTTPClient for a request.
func NewFilePolicyApplyParamsWithHTTPClient(client *http.Client) *FilePolicyApplyParams {
	return &FilePolicyApplyParams{
		HTTPClient: client,
	}
}

/*
FilePolicyApplyParams contains all the parameters to send to the API endpoint

	for the file policy apply operation.

	Typically these are written to a http.Request.
*/
type FilePolicyApplyParams struct {

	// Body.
	Body *models.StorageFilePolicyApplyRequest

	// ID.
	//
	// Format: int32
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the file policy apply params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FilePolicyApplyParams) WithDefaults() *FilePolicyApplyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the file policy apply params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FilePolicyApplyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the file policy apply params
func (o *FilePolicyApplyParams) WithTimeout(timeout time.Duration) *FilePolicyApplyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the file policy apply params
func (o *FilePolicyApplyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the file policy apply params
func (o *FilePolicyApplyParams) WithContext(ctx context.Context) *FilePolicyApplyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the file policy apply params
func (o *FilePolicyApplyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the file policy apply params
func (o *FilePolicyApplyParams) WithHTTPClient(client *http.Client) *FilePolicyApplyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the file policy apply params
func (o *FilePolicyApplyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the file policy apply params
func (o *FilePolicyApplyParams) WithBody(body *models.StorageFilePolicyApplyRequest) *FilePolicyApplyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the file policy apply params
func (o *FilePolicyApplyParams) SetBody(body *models.StorageFilePolicyApplyRequest) {
	o.Body = body
}

// WithID adds the id to the file policy apply params
func (o *FilePolicyApplyParams) WithID(id int32) *FilePolicyApplyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the file policy apply params
func (o *FilePolicyApplyParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FilePolicyApplyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
