// Code generated by go-swagger; DO NOT EDIT.

package file_policies_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// MovePositionFilePolicyReader is a Reader for the MovePositionFilePolicy structure.
type MovePositionFilePolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MovePositionFilePolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMovePositionFilePolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /storage/file_policies/{from_id}/to/{to_id}] MovePositionFilePolicy", response, response.Code())
	}
}

// NewMovePositionFilePolicyOK creates a MovePositionFilePolicyOK with default headers values
func NewMovePositionFilePolicyOK() *MovePositionFilePolicyOK {
	return &MovePositionFilePolicyOK{}
}

/*
MovePositionFilePolicyOK describes a response with status code 200, with default header values.

A successful response.
*/
type MovePositionFilePolicyOK struct {
	Payload *models.StorageMovePositionFilePolicyResponse
}

// IsSuccess returns true when this move position file policy Ok response has a 2xx status code
func (o *MovePositionFilePolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this move position file policy Ok response has a 3xx status code
func (o *MovePositionFilePolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this move position file policy Ok response has a 4xx status code
func (o *MovePositionFilePolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this move position file policy Ok response has a 5xx status code
func (o *MovePositionFilePolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this move position file policy Ok response a status code equal to that given
func (o *MovePositionFilePolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the move position file policy Ok response
func (o *MovePositionFilePolicyOK) Code() int {
	return 200
}

func (o *MovePositionFilePolicyOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /storage/file_policies/{from_id}/to/{to_id}][%d] movePositionFilePolicyOk %s", 200, payload)
}

func (o *MovePositionFilePolicyOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /storage/file_policies/{from_id}/to/{to_id}][%d] movePositionFilePolicyOk %s", 200, payload)
}

func (o *MovePositionFilePolicyOK) GetPayload() *models.StorageMovePositionFilePolicyResponse {
	return o.Payload
}

func (o *MovePositionFilePolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageMovePositionFilePolicyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
