// Code generated by go-swagger; DO NOT EDIT.

package agent_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// AgentStateHistoryReader is a Reader for the AgentStateHistory structure.
type AgentStateHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentStateHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAgentStateHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAgentStateHistoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAgentStateHistoryOK creates a AgentStateHistoryOK with default headers values
func NewAgentStateHistoryOK() *AgentStateHistoryOK {
	return &AgentStateHistoryOK{}
}

/*
AgentStateHistoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type AgentStateHistoryOK struct {
	Payload *models.EngineListAgentStateHistory
}

// IsSuccess returns true when this agent state history Ok response has a 2xx status code
func (o *AgentStateHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this agent state history Ok response has a 3xx status code
func (o *AgentStateHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent state history Ok response has a 4xx status code
func (o *AgentStateHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent state history Ok response has a 5xx status code
func (o *AgentStateHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this agent state history Ok response a status code equal to that given
func (o *AgentStateHistoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the agent state history Ok response
func (o *AgentStateHistoryOK) Code() int {
	return 200
}

func (o *AgentStateHistoryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/agents/{agent_id}/states/history][%d] agentStateHistoryOk %s", 200, payload)
}

func (o *AgentStateHistoryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/agents/{agent_id}/states/history][%d] agentStateHistoryOk %s", 200, payload)
}

func (o *AgentStateHistoryOK) GetPayload() *models.EngineListAgentStateHistory {
	return o.Payload
}

func (o *AgentStateHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListAgentStateHistory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAgentStateHistoryDefault creates a AgentStateHistoryDefault with default headers values
func NewAgentStateHistoryDefault(code int) *AgentStateHistoryDefault {
	return &AgentStateHistoryDefault{
		_statusCode: code,
	}
}

/*
AgentStateHistoryDefault describes a response with status code -1, with default header values.

Server error
*/
type AgentStateHistoryDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this agent state history default response has a 2xx status code
func (o *AgentStateHistoryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this agent state history default response has a 3xx status code
func (o *AgentStateHistoryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this agent state history default response has a 4xx status code
func (o *AgentStateHistoryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this agent state history default response has a 5xx status code
func (o *AgentStateHistoryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this agent state history default response a status code equal to that given
func (o *AgentStateHistoryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the agent state history default response
func (o *AgentStateHistoryDefault) Code() int {
	return o._statusCode
}

func (o *AgentStateHistoryDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/agents/{agent_id}/states/history][%d] AgentStateHistory default %s", o._statusCode, payload)
}

func (o *AgentStateHistoryDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/agents/{agent_id}/states/history][%d] AgentStateHistory default %s", o._statusCode, payload)
}

func (o *AgentStateHistoryDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *AgentStateHistoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
