// Code generated by go-swagger; DO NOT EDIT.

package status_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewUpdateStatusConditionParams creates a new UpdateStatusConditionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateStatusConditionParams() *UpdateStatusConditionParams {
	return &UpdateStatusConditionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateStatusConditionParamsWithTimeout creates a new UpdateStatusConditionParams object
// with the ability to set a timeout on a request.
func NewUpdateStatusConditionParamsWithTimeout(timeout time.Duration) *UpdateStatusConditionParams {
	return &UpdateStatusConditionParams{
		timeout: timeout,
	}
}

// NewUpdateStatusConditionParamsWithContext creates a new UpdateStatusConditionParams object
// with the ability to set a context for a request.
func NewUpdateStatusConditionParamsWithContext(ctx context.Context) *UpdateStatusConditionParams {
	return &UpdateStatusConditionParams{
		Context: ctx,
	}
}

// NewUpdateStatusConditionParamsWithHTTPClient creates a new UpdateStatusConditionParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateStatusConditionParamsWithHTTPClient(client *http.Client) *UpdateStatusConditionParams {
	return &UpdateStatusConditionParams{
		HTTPClient: client,
	}
}

/*
UpdateStatusConditionParams contains all the parameters to send to the API endpoint

	for the update status condition operation.

	Typically these are written to a http.Request.
*/
type UpdateStatusConditionParams struct {

	// ID.
	//
	// Format: int64
	ID string

	// Input.
	Input *models.CasesInputStatusCondition

	// StatusID.
	//
	// Format: int64
	StatusID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update status condition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateStatusConditionParams) WithDefaults() *UpdateStatusConditionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update status condition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateStatusConditionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update status condition params
func (o *UpdateStatusConditionParams) WithTimeout(timeout time.Duration) *UpdateStatusConditionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update status condition params
func (o *UpdateStatusConditionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update status condition params
func (o *UpdateStatusConditionParams) WithContext(ctx context.Context) *UpdateStatusConditionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update status condition params
func (o *UpdateStatusConditionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update status condition params
func (o *UpdateStatusConditionParams) WithHTTPClient(client *http.Client) *UpdateStatusConditionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update status condition params
func (o *UpdateStatusConditionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update status condition params
func (o *UpdateStatusConditionParams) WithID(id string) *UpdateStatusConditionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update status condition params
func (o *UpdateStatusConditionParams) SetID(id string) {
	o.ID = id
}

// WithInput adds the input to the update status condition params
func (o *UpdateStatusConditionParams) WithInput(input *models.CasesInputStatusCondition) *UpdateStatusConditionParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the update status condition params
func (o *UpdateStatusConditionParams) SetInput(input *models.CasesInputStatusCondition) {
	o.Input = input
}

// WithStatusID adds the statusID to the update status condition params
func (o *UpdateStatusConditionParams) WithStatusID(statusID string) *UpdateStatusConditionParams {
	o.SetStatusID(statusID)
	return o
}

// SetStatusID adds the statusId to the update status condition params
func (o *UpdateStatusConditionParams) SetStatusID(statusID string) {
	o.StatusID = statusID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateStatusConditionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	// path param status_id
	if err := r.SetPathParam("status_id", o.StatusID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
