// Code generated by go-swagger; DO NOT EDIT.

package system_setting_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// CreateSystemSettingReader is a Reader for the CreateSystemSetting structure.
type CreateSystemSettingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSystemSettingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSystemSettingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateSystemSettingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSystemSettingOK creates a CreateSystemSettingOK with default headers values
func NewCreateSystemSettingOK() *CreateSystemSettingOK {
	return &CreateSystemSettingOK{}
}

/*
CreateSystemSettingOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateSystemSettingOK struct {
	Payload *models.EngineSystemSetting
}

// IsSuccess returns true when this create system setting Ok response has a 2xx status code
func (o *CreateSystemSettingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create system setting Ok response has a 3xx status code
func (o *CreateSystemSettingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create system setting Ok response has a 4xx status code
func (o *CreateSystemSettingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create system setting Ok response has a 5xx status code
func (o *CreateSystemSettingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create system setting Ok response a status code equal to that given
func (o *CreateSystemSettingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create system setting Ok response
func (o *CreateSystemSettingOK) Code() int {
	return 200
}

func (o *CreateSystemSettingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /settings][%d] createSystemSettingOk %s", 200, payload)
}

func (o *CreateSystemSettingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /settings][%d] createSystemSettingOk %s", 200, payload)
}

func (o *CreateSystemSettingOK) GetPayload() *models.EngineSystemSetting {
	return o.Payload
}

func (o *CreateSystemSettingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineSystemSetting)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSystemSettingDefault creates a CreateSystemSettingDefault with default headers values
func NewCreateSystemSettingDefault(code int) *CreateSystemSettingDefault {
	return &CreateSystemSettingDefault{
		_statusCode: code,
	}
}

/*
CreateSystemSettingDefault describes a response with status code -1, with default header values.

Server error
*/
type CreateSystemSettingDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this create system setting default response has a 2xx status code
func (o *CreateSystemSettingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create system setting default response has a 3xx status code
func (o *CreateSystemSettingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create system setting default response has a 4xx status code
func (o *CreateSystemSettingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create system setting default response has a 5xx status code
func (o *CreateSystemSettingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create system setting default response a status code equal to that given
func (o *CreateSystemSettingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create system setting default response
func (o *CreateSystemSettingDefault) Code() int {
	return o._statusCode
}

func (o *CreateSystemSettingDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /settings][%d] CreateSystemSetting default %s", o._statusCode, payload)
}

func (o *CreateSystemSettingDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /settings][%d] CreateSystemSetting default %s", o._statusCode, payload)
}

func (o *CreateSystemSettingDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *CreateSystemSettingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
