// Code generated by go-swagger; DO NOT EDIT.

package access_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// AccessStoreListObjectAccessReader is a Reader for the AccessStoreListObjectAccess structure.
type AccessStoreListObjectAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccessStoreListObjectAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccessStoreListObjectAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /{object.name}/{object.id}/acl] AccessStore_ListObjectAccess", response, response.Code())
	}
}

// NewAccessStoreListObjectAccessOK creates a AccessStoreListObjectAccessOK with default headers values
func NewAccessStoreListObjectAccessOK() *AccessStoreListObjectAccessOK {
	return &AccessStoreListObjectAccessOK{}
}

/*
AccessStoreListObjectAccessOK describes a response with status code 200, with default header values.

A successful response.
*/
type AccessStoreListObjectAccessOK struct {
	Payload *models.APIListAccessResponseV1
}

// IsSuccess returns true when this access store list object access Ok response has a 2xx status code
func (o *AccessStoreListObjectAccessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this access store list object access Ok response has a 3xx status code
func (o *AccessStoreListObjectAccessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this access store list object access Ok response has a 4xx status code
func (o *AccessStoreListObjectAccessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this access store list object access Ok response has a 5xx status code
func (o *AccessStoreListObjectAccessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this access store list object access Ok response a status code equal to that given
func (o *AccessStoreListObjectAccessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the access store list object access Ok response
func (o *AccessStoreListObjectAccessOK) Code() int {
	return 200
}

func (o *AccessStoreListObjectAccessOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /{object.name}/{object.id}/acl][%d] accessStoreListObjectAccessOk %s", 200, payload)
}

func (o *AccessStoreListObjectAccessOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /{object.name}/{object.id}/acl][%d] accessStoreListObjectAccessOk %s", 200, payload)
}

func (o *AccessStoreListObjectAccessOK) GetPayload() *models.APIListAccessResponseV1 {
	return o.Payload
}

func (o *AccessStoreListObjectAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIListAccessResponseV1)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
