// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewRolesCreateRoleParams creates a new RolesCreateRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRolesCreateRoleParams() *RolesCreateRoleParams {
	return &RolesCreateRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRolesCreateRoleParamsWithTimeout creates a new RolesCreateRoleParams object
// with the ability to set a timeout on a request.
func NewRolesCreateRoleParamsWithTimeout(timeout time.Duration) *RolesCreateRoleParams {
	return &RolesCreateRoleParams{
		timeout: timeout,
	}
}

// NewRolesCreateRoleParamsWithContext creates a new RolesCreateRoleParams object
// with the ability to set a context for a request.
func NewRolesCreateRoleParamsWithContext(ctx context.Context) *RolesCreateRoleParams {
	return &RolesCreateRoleParams{
		Context: ctx,
	}
}

// NewRolesCreateRoleParamsWithHTTPClient creates a new RolesCreateRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewRolesCreateRoleParamsWithHTTPClient(client *http.Client) *RolesCreateRoleParams {
	return &RolesCreateRoleParams{
		HTTPClient: client,
	}
}

/*
RolesCreateRoleParams contains all the parameters to send to the API endpoint

	for the roles create role operation.

	Typically these are written to a http.Request.
*/
type RolesCreateRoleParams struct {

	// Body.
	Body *models.APICreateRoleRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the roles create role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RolesCreateRoleParams) WithDefaults() *RolesCreateRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the roles create role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RolesCreateRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the roles create role params
func (o *RolesCreateRoleParams) WithTimeout(timeout time.Duration) *RolesCreateRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the roles create role params
func (o *RolesCreateRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the roles create role params
func (o *RolesCreateRoleParams) WithContext(ctx context.Context) *RolesCreateRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the roles create role params
func (o *RolesCreateRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the roles create role params
func (o *RolesCreateRoleParams) WithHTTPClient(client *http.Client) *RolesCreateRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the roles create role params
func (o *RolesCreateRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the roles create role params
func (o *RolesCreateRoleParams) WithBody(body *models.APICreateRoleRequest) *RolesCreateRoleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the roles create role params
func (o *RolesCreateRoleParams) SetBody(body *models.APICreateRoleRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RolesCreateRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
