// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// RolesUpdateRole2Reader is a Reader for the RolesUpdateRole2 structure.
type RolesUpdateRole2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RolesUpdateRole2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRolesUpdateRole2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /roles/{role.id}] Roles_UpdateRole2", response, response.Code())
	}
}

// NewRolesUpdateRole2OK creates a RolesUpdateRole2OK with default headers values
func NewRolesUpdateRole2OK() *RolesUpdateRole2OK {
	return &RolesUpdateRole2OK{}
}

/*
RolesUpdateRole2OK describes a response with status code 200, with default header values.

A successful response.
*/
type RolesUpdateRole2OK struct {
	Payload *models.APIUpdateRoleResponse
}

// IsSuccess returns true when this roles update role2 Ok response has a 2xx status code
func (o *RolesUpdateRole2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this roles update role2 Ok response has a 3xx status code
func (o *RolesUpdateRole2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this roles update role2 Ok response has a 4xx status code
func (o *RolesUpdateRole2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this roles update role2 Ok response has a 5xx status code
func (o *RolesUpdateRole2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this roles update role2 Ok response a status code equal to that given
func (o *RolesUpdateRole2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the roles update role2 Ok response
func (o *RolesUpdateRole2OK) Code() int {
	return 200
}

func (o *RolesUpdateRole2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /roles/{role.id}][%d] rolesUpdateRole2Ok %s", 200, payload)
}

func (o *RolesUpdateRole2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /roles/{role.id}][%d] rolesUpdateRole2Ok %s", 200, payload)
}

func (o *RolesUpdateRole2OK) GetPayload() *models.APIUpdateRoleResponse {
	return o.Payload
}

func (o *RolesUpdateRole2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUpdateRoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
