// Code generated by go-swagger; DO NOT EDIT.

package close_reason_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// LocateCloseReasonGroupReader is a Reader for the LocateCloseReasonGroup structure.
type LocateCloseReasonGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocateCloseReasonGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocateCloseReasonGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocateCloseReasonGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocateCloseReasonGroupOK creates a LocateCloseReasonGroupOK with default headers values
func NewLocateCloseReasonGroupOK() *LocateCloseReasonGroupOK {
	return &LocateCloseReasonGroupOK{}
}

/*
LocateCloseReasonGroupOK describes a response with status code 200, with default header values.

A successful response.
*/
type LocateCloseReasonGroupOK struct {
	Payload *models.CasesLocateCloseReasonGroupResponse
}

// IsSuccess returns true when this locate close reason group Ok response has a 2xx status code
func (o *LocateCloseReasonGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this locate close reason group Ok response has a 3xx status code
func (o *LocateCloseReasonGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this locate close reason group Ok response has a 4xx status code
func (o *LocateCloseReasonGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this locate close reason group Ok response has a 5xx status code
func (o *LocateCloseReasonGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this locate close reason group Ok response a status code equal to that given
func (o *LocateCloseReasonGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the locate close reason group Ok response
func (o *LocateCloseReasonGroupOK) Code() int {
	return 200
}

func (o *LocateCloseReasonGroupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cases/close_reason_groups/{id}][%d] locateCloseReasonGroupOk %s", 200, payload)
}

func (o *LocateCloseReasonGroupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cases/close_reason_groups/{id}][%d] locateCloseReasonGroupOk %s", 200, payload)
}

func (o *LocateCloseReasonGroupOK) GetPayload() *models.CasesLocateCloseReasonGroupResponse {
	return o.Payload
}

func (o *LocateCloseReasonGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CasesLocateCloseReasonGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLocateCloseReasonGroupDefault creates a LocateCloseReasonGroupDefault with default headers values
func NewLocateCloseReasonGroupDefault(code int) *LocateCloseReasonGroupDefault {
	return &LocateCloseReasonGroupDefault{
		_statusCode: code,
	}
}

/*
LocateCloseReasonGroupDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type LocateCloseReasonGroupDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this locate close reason group default response has a 2xx status code
func (o *LocateCloseReasonGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this locate close reason group default response has a 3xx status code
func (o *LocateCloseReasonGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this locate close reason group default response has a 4xx status code
func (o *LocateCloseReasonGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this locate close reason group default response has a 5xx status code
func (o *LocateCloseReasonGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this locate close reason group default response a status code equal to that given
func (o *LocateCloseReasonGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the locate close reason group default response
func (o *LocateCloseReasonGroupDefault) Code() int {
	return o._statusCode
}

func (o *LocateCloseReasonGroupDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cases/close_reason_groups/{id}][%d] LocateCloseReasonGroup default %s", o._statusCode, payload)
}

func (o *LocateCloseReasonGroupDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cases/close_reason_groups/{id}][%d] LocateCloseReasonGroup default %s", o._statusCode, payload)
}

func (o *LocateCloseReasonGroupDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *LocateCloseReasonGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
