// Code generated by go-swagger; DO NOT EDIT.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// DomainsUpdateDomain2Reader is a Reader for the DomainsUpdateDomain2 structure.
type DomainsUpdateDomain2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DomainsUpdateDomain2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDomainsUpdateDomain2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /domains/{domain.dc}] Domains_UpdateDomain2", response, response.Code())
	}
}

// NewDomainsUpdateDomain2OK creates a DomainsUpdateDomain2OK with default headers values
func NewDomainsUpdateDomain2OK() *DomainsUpdateDomain2OK {
	return &DomainsUpdateDomain2OK{}
}

/*
DomainsUpdateDomain2OK describes a response with status code 200, with default header values.

A successful response.
*/
type DomainsUpdateDomain2OK struct {
	Payload *models.APIUpdateDomainResponse
}

// IsSuccess returns true when this domains update domain2 Ok response has a 2xx status code
func (o *DomainsUpdateDomain2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this domains update domain2 Ok response has a 3xx status code
func (o *DomainsUpdateDomain2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this domains update domain2 Ok response has a 4xx status code
func (o *DomainsUpdateDomain2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this domains update domain2 Ok response has a 5xx status code
func (o *DomainsUpdateDomain2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this domains update domain2 Ok response a status code equal to that given
func (o *DomainsUpdateDomain2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the domains update domain2 Ok response
func (o *DomainsUpdateDomain2OK) Code() int {
	return 200
}

func (o *DomainsUpdateDomain2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /domains/{domain.dc}][%d] domainsUpdateDomain2Ok %s", 200, payload)
}

func (o *DomainsUpdateDomain2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /domains/{domain.dc}][%d] domainsUpdateDomain2Ok %s", 200, payload)
}

func (o *DomainsUpdateDomain2OK) GetPayload() *models.APIUpdateDomainResponse {
	return o.Payload
}

func (o *DomainsUpdateDomain2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUpdateDomainResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
