// Code generated by go-swagger; DO NOT EDIT.

package call_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// EavesdropCallReader is a Reader for the EavesdropCall structure.
type EavesdropCallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EavesdropCallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEavesdropCallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEavesdropCallDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEavesdropCallOK creates a EavesdropCallOK with default headers values
func NewEavesdropCallOK() *EavesdropCallOK {
	return &EavesdropCallOK{}
}

/*
EavesdropCallOK describes a response with status code 200, with default header values.

A successful response.
*/
type EavesdropCallOK struct {
	Payload *models.EngineCreateCallResponse
}

// IsSuccess returns true when this eavesdrop call Ok response has a 2xx status code
func (o *EavesdropCallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this eavesdrop call Ok response has a 3xx status code
func (o *EavesdropCallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this eavesdrop call Ok response has a 4xx status code
func (o *EavesdropCallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this eavesdrop call Ok response has a 5xx status code
func (o *EavesdropCallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this eavesdrop call Ok response a status code equal to that given
func (o *EavesdropCallOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the eavesdrop call Ok response
func (o *EavesdropCallOK) Code() int {
	return 200
}

func (o *EavesdropCallOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] eavesdropCallOk %s", 200, payload)
}

func (o *EavesdropCallOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] eavesdropCallOk %s", 200, payload)
}

func (o *EavesdropCallOK) GetPayload() *models.EngineCreateCallResponse {
	return o.Payload
}

func (o *EavesdropCallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineCreateCallResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEavesdropCallDefault creates a EavesdropCallDefault with default headers values
func NewEavesdropCallDefault(code int) *EavesdropCallDefault {
	return &EavesdropCallDefault{
		_statusCode: code,
	}
}

/*
EavesdropCallDefault describes a response with status code -1, with default header values.

Server error
*/
type EavesdropCallDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this eavesdrop call default response has a 2xx status code
func (o *EavesdropCallDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this eavesdrop call default response has a 3xx status code
func (o *EavesdropCallDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this eavesdrop call default response has a 4xx status code
func (o *EavesdropCallDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this eavesdrop call default response has a 5xx status code
func (o *EavesdropCallDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this eavesdrop call default response a status code equal to that given
func (o *EavesdropCallDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the eavesdrop call default response
func (o *EavesdropCallDefault) Code() int {
	return o._statusCode
}

func (o *EavesdropCallDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] EavesdropCall default %s", o._statusCode, payload)
}

func (o *EavesdropCallDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /calls/active/{id}/eavesdrop][%d] EavesdropCall default %s", o._statusCode, payload)
}

func (o *EavesdropCallDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *EavesdropCallDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
