// Code generated by go-swagger; DO NOT EDIT.

package agent_pause_cause_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// CreateAgentPauseCauseReader is a Reader for the CreateAgentPauseCause structure.
type CreateAgentPauseCauseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAgentPauseCauseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAgentPauseCauseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateAgentPauseCauseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateAgentPauseCauseOK creates a CreateAgentPauseCauseOK with default headers values
func NewCreateAgentPauseCauseOK() *CreateAgentPauseCauseOK {
	return &CreateAgentPauseCauseOK{}
}

/*
CreateAgentPauseCauseOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateAgentPauseCauseOK struct {
	Payload *models.EngineAgentPauseCause
}

// IsSuccess returns true when this create agent pause cause Ok response has a 2xx status code
func (o *CreateAgentPauseCauseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create agent pause cause Ok response has a 3xx status code
func (o *CreateAgentPauseCauseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create agent pause cause Ok response has a 4xx status code
func (o *CreateAgentPauseCauseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create agent pause cause Ok response has a 5xx status code
func (o *CreateAgentPauseCauseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create agent pause cause Ok response a status code equal to that given
func (o *CreateAgentPauseCauseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create agent pause cause Ok response
func (o *CreateAgentPauseCauseOK) Code() int {
	return 200
}

func (o *CreateAgentPauseCauseOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /call_center/pause_causes][%d] createAgentPauseCauseOk %s", 200, payload)
}

func (o *CreateAgentPauseCauseOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /call_center/pause_causes][%d] createAgentPauseCauseOk %s", 200, payload)
}

func (o *CreateAgentPauseCauseOK) GetPayload() *models.EngineAgentPauseCause {
	return o.Payload
}

func (o *CreateAgentPauseCauseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAgentPauseCause)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAgentPauseCauseDefault creates a CreateAgentPauseCauseDefault with default headers values
func NewCreateAgentPauseCauseDefault(code int) *CreateAgentPauseCauseDefault {
	return &CreateAgentPauseCauseDefault{
		_statusCode: code,
	}
}

/*
CreateAgentPauseCauseDefault describes a response with status code -1, with default header values.

Server error
*/
type CreateAgentPauseCauseDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this create agent pause cause default response has a 2xx status code
func (o *CreateAgentPauseCauseDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create agent pause cause default response has a 3xx status code
func (o *CreateAgentPauseCauseDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create agent pause cause default response has a 4xx status code
func (o *CreateAgentPauseCauseDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create agent pause cause default response has a 5xx status code
func (o *CreateAgentPauseCauseDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create agent pause cause default response a status code equal to that given
func (o *CreateAgentPauseCauseDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create agent pause cause default response
func (o *CreateAgentPauseCauseDefault) Code() int {
	return o._statusCode
}

func (o *CreateAgentPauseCauseDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /call_center/pause_causes][%d] CreateAgentPauseCause default %s", o._statusCode, payload)
}

func (o *CreateAgentPauseCauseDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /call_center/pause_causes][%d] CreateAgentPauseCause default %s", o._statusCode, payload)
}

func (o *CreateAgentPauseCauseDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *CreateAgentPauseCauseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
