// Code generated by go-swagger; DO NOT EDIT.

package web_hook_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// SearchWebHookReader is a Reader for the SearchWebHook structure.
type SearchWebHookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchWebHookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchWebHookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSearchWebHookDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSearchWebHookOK creates a SearchWebHookOK with default headers values
func NewSearchWebHookOK() *SearchWebHookOK {
	return &SearchWebHookOK{}
}

/*
SearchWebHookOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchWebHookOK struct {
	Payload *models.EngineListWebHook
}

// IsSuccess returns true when this search web hook Ok response has a 2xx status code
func (o *SearchWebHookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search web hook Ok response has a 3xx status code
func (o *SearchWebHookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search web hook Ok response has a 4xx status code
func (o *SearchWebHookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search web hook Ok response has a 5xx status code
func (o *SearchWebHookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search web hook Ok response a status code equal to that given
func (o *SearchWebHookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search web hook Ok response
func (o *SearchWebHookOK) Code() int {
	return 200
}

func (o *SearchWebHookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hook][%d] searchWebHookOk %s", 200, payload)
}

func (o *SearchWebHookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hook][%d] searchWebHookOk %s", 200, payload)
}

func (o *SearchWebHookOK) GetPayload() *models.EngineListWebHook {
	return o.Payload
}

func (o *SearchWebHookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListWebHook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchWebHookDefault creates a SearchWebHookDefault with default headers values
func NewSearchWebHookDefault(code int) *SearchWebHookDefault {
	return &SearchWebHookDefault{
		_statusCode: code,
	}
}

/*
SearchWebHookDefault describes a response with status code -1, with default header values.

Server error
*/
type SearchWebHookDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this search web hook default response has a 2xx status code
func (o *SearchWebHookDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search web hook default response has a 3xx status code
func (o *SearchWebHookDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search web hook default response has a 4xx status code
func (o *SearchWebHookDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search web hook default response has a 5xx status code
func (o *SearchWebHookDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search web hook default response a status code equal to that given
func (o *SearchWebHookDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the search web hook default response
func (o *SearchWebHookDefault) Code() int {
	return o._statusCode
}

func (o *SearchWebHookDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hook][%d] SearchWebHook default %s", o._statusCode, payload)
}

func (o *SearchWebHookDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hook][%d] SearchWebHook default %s", o._statusCode, payload)
}

func (o *SearchWebHookDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *SearchWebHookDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
