// Code generated by go-swagger; DO NOT EDIT.

package skill_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// SearchSkillAgentReader is a Reader for the SearchSkillAgent structure.
type SearchSkillAgentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchSkillAgentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchSkillAgentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSearchSkillAgentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSearchSkillAgentOK creates a SearchSkillAgentOK with default headers values
func NewSearchSkillAgentOK() *SearchSkillAgentOK {
	return &SearchSkillAgentOK{}
}

/*
SearchSkillAgentOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchSkillAgentOK struct {
	Payload *models.EngineListSkillAgent
}

// IsSuccess returns true when this search skill agent Ok response has a 2xx status code
func (o *SearchSkillAgentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search skill agent Ok response has a 3xx status code
func (o *SearchSkillAgentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search skill agent Ok response has a 4xx status code
func (o *SearchSkillAgentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search skill agent Ok response has a 5xx status code
func (o *SearchSkillAgentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search skill agent Ok response a status code equal to that given
func (o *SearchSkillAgentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search skill agent Ok response
func (o *SearchSkillAgentOK) Code() int {
	return 200
}

func (o *SearchSkillAgentOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/skills/{skill_id}/agents][%d] searchSkillAgentOk %s", 200, payload)
}

func (o *SearchSkillAgentOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/skills/{skill_id}/agents][%d] searchSkillAgentOk %s", 200, payload)
}

func (o *SearchSkillAgentOK) GetPayload() *models.EngineListSkillAgent {
	return o.Payload
}

func (o *SearchSkillAgentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListSkillAgent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchSkillAgentDefault creates a SearchSkillAgentDefault with default headers values
func NewSearchSkillAgentDefault(code int) *SearchSkillAgentDefault {
	return &SearchSkillAgentDefault{
		_statusCode: code,
	}
}

/*
SearchSkillAgentDefault describes a response with status code -1, with default header values.

Server error
*/
type SearchSkillAgentDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this search skill agent default response has a 2xx status code
func (o *SearchSkillAgentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search skill agent default response has a 3xx status code
func (o *SearchSkillAgentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search skill agent default response has a 4xx status code
func (o *SearchSkillAgentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search skill agent default response has a 5xx status code
func (o *SearchSkillAgentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search skill agent default response a status code equal to that given
func (o *SearchSkillAgentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the search skill agent default response
func (o *SearchSkillAgentDefault) Code() int {
	return o._statusCode
}

func (o *SearchSkillAgentDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/skills/{skill_id}/agents][%d] SearchSkillAgent default %s", o._statusCode, payload)
}

func (o *SearchSkillAgentDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/skills/{skill_id}/agents][%d] SearchSkillAgent default %s", o._statusCode, payload)
}

func (o *SearchSkillAgentDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *SearchSkillAgentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
