// Code generated by go-swagger; DO NOT EDIT.

package i_m_clients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIMClientsListIMClientsParams creates a new IMClientsListIMClientsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIMClientsListIMClientsParams() *IMClientsListIMClientsParams {
	return &IMClientsListIMClientsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIMClientsListIMClientsParamsWithTimeout creates a new IMClientsListIMClientsParams object
// with the ability to set a timeout on a request.
func NewIMClientsListIMClientsParamsWithTimeout(timeout time.Duration) *IMClientsListIMClientsParams {
	return &IMClientsListIMClientsParams{
		timeout: timeout,
	}
}

// NewIMClientsListIMClientsParamsWithContext creates a new IMClientsListIMClientsParams object
// with the ability to set a context for a request.
func NewIMClientsListIMClientsParamsWithContext(ctx context.Context) *IMClientsListIMClientsParams {
	return &IMClientsListIMClientsParams{
		Context: ctx,
	}
}

// NewIMClientsListIMClientsParamsWithHTTPClient creates a new IMClientsListIMClientsParams object
// with the ability to set a custom HTTPClient for a request.
func NewIMClientsListIMClientsParamsWithHTTPClient(client *http.Client) *IMClientsListIMClientsParams {
	return &IMClientsListIMClientsParams{
		HTTPClient: client,
	}
}

/*
IMClientsListIMClientsParams contains all the parameters to send to the API endpoint

	for the i m clients list i m clients operation.

	Typically these are written to a http.Request.
*/
type IMClientsListIMClientsParams struct {

	/* ContactID.

	   Link contact ID.
	*/
	ContactID string

	/* Fields.

	   Fields to be retrieved into result.
	*/
	Fields []string

	/* ID.

	   Link(s) with unique ID only.
	*/
	ID []string

	/* Page.

	   Page number of result dataset records. offset = (page*size)

	   Format: int32
	*/
	Page *int32

	/* Q.

	     Search term: IMClient.
	`?` - matches any one character
	`*` - matches 0 or more characters
	Search fields: {user,app}
	*/
	Q *string

	/* Size.

	   Size count of records on result page. limit = (size++)

	   Format: int32
	*/
	Size *int32

	/* Sort.

	   Sort the result according to fields.
	*/
	Sort []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the i m clients list i m clients params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IMClientsListIMClientsParams) WithDefaults() *IMClientsListIMClientsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the i m clients list i m clients params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IMClientsListIMClientsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithTimeout(timeout time.Duration) *IMClientsListIMClientsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithContext(ctx context.Context) *IMClientsListIMClientsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithHTTPClient(client *http.Client) *IMClientsListIMClientsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactID adds the contactID to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithContactID(contactID string) *IMClientsListIMClientsParams {
	o.SetContactID(contactID)
	return o
}

// SetContactID adds the contactId to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetContactID(contactID string) {
	o.ContactID = contactID
}

// WithFields adds the fields to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithFields(fields []string) *IMClientsListIMClientsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithID adds the id to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithID(id []string) *IMClientsListIMClientsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetID(id []string) {
	o.ID = id
}

// WithPage adds the page to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithPage(page *int32) *IMClientsListIMClientsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetPage(page *int32) {
	o.Page = page
}

// WithQ adds the q to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithQ(q *string) *IMClientsListIMClientsParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetQ(q *string) {
	o.Q = q
}

// WithSize adds the size to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithSize(size *int32) *IMClientsListIMClientsParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetSize(size *int32) {
	o.Size = size
}

// WithSort adds the sort to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) WithSort(sort []string) *IMClientsListIMClientsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the i m clients list i m clients params
func (o *IMClientsListIMClientsParams) SetSort(sort []string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *IMClientsListIMClientsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contact_id
	if err := r.SetPathParam("contact_id", o.ContactID); err != nil {
		return err
	}

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}

	if o.ID != nil {

		// binding items for id
		joinedID := o.bindParamID(reg)

		// query array param id
		if err := r.SetQueryParam("id", joinedID...); err != nil {
			return err
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int32

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Size != nil {

		// query param size
		var qrSize int32

		if o.Size != nil {
			qrSize = *o.Size
		}
		qSize := swag.FormatInt32(qrSize)
		if qSize != "" {

			if err := r.SetQueryParam("size", qSize); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// binding items for sort
		joinedSort := o.bindParamSort(reg)

		// query array param sort
		if err := r.SetQueryParam("sort", joinedSort...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamIMClientsListIMClients binds the parameter fields
func (o *IMClientsListIMClientsParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldsIS := swag.JoinByFormat(fieldsIC, "multi")

	return fieldsIS
}

// bindParamIMClientsListIMClients binds the parameter id
func (o *IMClientsListIMClientsParams) bindParamID(formats strfmt.Registry) []string {
	iDIR := o.ID

	var iDIC []string
	for _, iDIIR := range iDIR { // explode []string

		iDIIV := iDIIR // string as string
		iDIC = append(iDIC, iDIIV)
	}

	// items.CollectionFormat: "multi"
	iDIS := swag.JoinByFormat(iDIC, "multi")

	return iDIS
}

// bindParamIMClientsListIMClients binds the parameter sort
func (o *IMClientsListIMClientsParams) bindParamSort(formats strfmt.Registry) []string {
	sortIR := o.Sort

	var sortIC []string
	for _, sortIIR := range sortIR { // explode []string

		sortIIV := sortIIR // string as string
		sortIC = append(sortIC, sortIIV)
	}

	// items.CollectionFormat: "multi"
	sortIS := swag.JoinByFormat(sortIC, "multi")

	return sortIS
}
