// Code generated by go-swagger; DO NOT EDIT.

package dictionaries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// New creates a new dictionaries API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for dictionaries API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DictionariesCreateData(repo string, record interface{}, opts ...ClientOption) (*DictionariesCreateDataOK, error)
	DictionariesCreateDataWithParams(params *DictionariesCreateDataParams, opts ...ClientOption) (*DictionariesCreateDataOK, error)

	DictionariesCreateType(repo string, input *models.WebitelProtoDataInputDictionary, opts ...ClientOption) (*DictionariesCreateTypeOK, error)
	DictionariesCreateTypeWithParams(params *DictionariesCreateTypeParams, opts ...ClientOption) (*DictionariesCreateTypeOK, error)

	DictionariesDeleteData(params *DictionariesDeleteDataParams, opts ...ClientOption) (*DictionariesDeleteDataOK, error)

	DictionariesDeleteData2(params *DictionariesDeleteData2Params, opts ...ClientOption) (*DictionariesDeleteData2OK, error)

	DictionariesDeleteType(params *DictionariesDeleteTypeParams, opts ...ClientOption) (*DictionariesDeleteTypeOK, error)

	DictionariesImportCSV(repo string, body *models.DictionariesImportCSVParamsBody, opts ...ClientOption) (*DictionariesImportCSVOK, error)
	DictionariesImportCSVWithParams(params *DictionariesImportCSVParams, opts ...ClientOption) (*DictionariesImportCSVOK, error)

	DictionariesLocateData(params *DictionariesLocateDataParams, opts ...ClientOption) (*DictionariesLocateDataOK, error)

	DictionariesLocateType(repo string, opts ...ClientOption) (*DictionariesLocateTypeOK, error)
	DictionariesLocateTypeWithParams(params *DictionariesLocateTypeParams, opts ...ClientOption) (*DictionariesLocateTypeOK, error)

	DictionariesSearchData(params *DictionariesSearchDataParams, opts ...ClientOption) (*DictionariesSearchDataOK, error)

	DictionariesSearchType(params *DictionariesSearchTypeParams, opts ...ClientOption) (*DictionariesSearchTypeOK, error)

	DictionariesUpdateData(params *DictionariesUpdateDataParams, opts ...ClientOption) (*DictionariesUpdateDataOK, error)

	DictionariesUpdateData2(params *DictionariesUpdateData2Params, opts ...ClientOption) (*DictionariesUpdateData2OK, error)

	DictionariesUpdateType(repo string, input *models.WebitelProtoDataInputDictionary, opts ...ClientOption) (*DictionariesUpdateTypeOK, error)
	DictionariesUpdateTypeWithParams(params *DictionariesUpdateTypeParams, opts ...ClientOption) (*DictionariesUpdateTypeOK, error)

	DictionariesUpdateType2(repo string, input *models.WebitelProtoDataInputDictionary, opts ...ClientOption) (*DictionariesUpdateType2OK, error)
	DictionariesUpdateType2WithParams(params *DictionariesUpdateType2Params, opts ...ClientOption) (*DictionariesUpdateType2OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DictionariesCreateData creates a dictionary record

(Record) {
*/
func (a *Client) DictionariesCreateData(repo string, record interface{}, opts ...ClientOption) (*DictionariesCreateDataOK, error) {
	params := NewDictionariesCreateDataParams().WithRecord(record).WithRepo(repo)
	return a.DictionariesCreateDataWithParams(params, opts...)
}

func (a *Client) DictionariesCreateDataWithParams(params *DictionariesCreateDataParams, opts ...ClientOption) (*DictionariesCreateDataOK, error) {
	if params == nil {
		params = NewDictionariesCreateDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_CreateData",
		Method:             "POST",
		PathPattern:        "/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesCreateDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesCreateDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_CreateData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesCreateType creates custom dictionary

(Dictionary) {
*/
func (a *Client) DictionariesCreateType(repo string, input *models.WebitelProtoDataInputDictionary, opts ...ClientOption) (*DictionariesCreateTypeOK, error) {
	params := NewDictionariesCreateTypeParams().WithInput(input).WithRepo(repo)
	return a.DictionariesCreateTypeWithParams(params, opts...)
}

func (a *Client) DictionariesCreateTypeWithParams(params *DictionariesCreateTypeParams, opts ...ClientOption) (*DictionariesCreateTypeOK, error) {
	if params == nil {
		params = NewDictionariesCreateTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_CreateType",
		Method:             "POST",
		PathPattern:        "/types/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesCreateTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesCreateTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_CreateType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesDeleteData deletes a dictionary records
*/

func (a *Client) DictionariesDeleteData(params *DictionariesDeleteDataParams, opts ...ClientOption) (*DictionariesDeleteDataOK, error) {
	if params == nil {
		params = NewDictionariesDeleteDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_DeleteData",
		Method:             "DELETE",
		PathPattern:        "/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesDeleteDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesDeleteDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_DeleteData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesDeleteData2 deletes a dictionary records
*/

func (a *Client) DictionariesDeleteData2(params *DictionariesDeleteData2Params, opts ...ClientOption) (*DictionariesDeleteData2OK, error) {
	if params == nil {
		params = NewDictionariesDeleteData2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_DeleteData2",
		Method:             "DELETE",
		PathPattern:        "/dictionaries/{repo}/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesDeleteData2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesDeleteData2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_DeleteData2: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesDeleteType deletes custom dictionaries

(DictionaryList) {
*/

func (a *Client) DictionariesDeleteType(params *DictionariesDeleteTypeParams, opts ...ClientOption) (*DictionariesDeleteTypeOK, error) {
	if params == nil {
		params = NewDictionariesDeleteTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_DeleteType",
		Method:             "DELETE",
		PathPattern:        "/types/dictionaries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesDeleteTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesDeleteTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_DeleteType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesImportCSV imports dataset from CSV file
*/
func (a *Client) DictionariesImportCSV(repo string, body *models.DictionariesImportCSVParamsBody, opts ...ClientOption) (*DictionariesImportCSVOK, error) {
	params := NewDictionariesImportCSVParams().WithBody(body).WithRepo(repo)
	return a.DictionariesImportCSVWithParams(params, opts...)
}

func (a *Client) DictionariesImportCSVWithParams(params *DictionariesImportCSVParams, opts ...ClientOption) (*DictionariesImportCSVOK, error) {
	if params == nil {
		params = NewDictionariesImportCSVParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_ImportCSV",
		Method:             "POST",
		PathPattern:        "/dictionaries/{repo}/csv",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesImportCSVReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesImportCSVOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_ImportCSV: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesLocateData locates a dictionary record

(Record) {
*/

func (a *Client) DictionariesLocateData(params *DictionariesLocateDataParams, opts ...ClientOption) (*DictionariesLocateDataOK, error) {
	if params == nil {
		params = NewDictionariesLocateDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_LocateData",
		Method:             "GET",
		PathPattern:        "/dictionaries/{repo}/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesLocateDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesLocateDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_LocateData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesLocateType locates the dictionary type

(Dictionary) {
*/
func (a *Client) DictionariesLocateType(repo string, opts ...ClientOption) (*DictionariesLocateTypeOK, error) {
	params := NewDictionariesLocateTypeParams().WithRepo(repo)
	return a.DictionariesLocateTypeWithParams(params, opts...)
}

func (a *Client) DictionariesLocateTypeWithParams(params *DictionariesLocateTypeParams, opts ...ClientOption) (*DictionariesLocateTypeOK, error) {
	if params == nil {
		params = NewDictionariesLocateTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_LocateType",
		Method:             "GET",
		PathPattern:        "/types/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesLocateTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesLocateTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_LocateType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesSearchData lookups a dictionary dataset
*/

func (a *Client) DictionariesSearchData(params *DictionariesSearchDataParams, opts ...ClientOption) (*DictionariesSearchDataOK, error) {
	if params == nil {
		params = NewDictionariesSearchDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_SearchData",
		Method:             "GET",
		PathPattern:        "/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesSearchDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesSearchDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_SearchData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesSearchType lookups dictionaries data types
*/

func (a *Client) DictionariesSearchType(params *DictionariesSearchTypeParams, opts ...ClientOption) (*DictionariesSearchTypeOK, error) {
	if params == nil {
		params = NewDictionariesSearchTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_SearchType",
		Method:             "GET",
		PathPattern:        "/types/dictionaries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesSearchTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesSearchTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_SearchType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesUpdateData updates a dictionary record

(Record) {
*/

func (a *Client) DictionariesUpdateData(params *DictionariesUpdateDataParams, opts ...ClientOption) (*DictionariesUpdateDataOK, error) {
	if params == nil {
		params = NewDictionariesUpdateDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_UpdateData",
		Method:             "PATCH",
		PathPattern:        "/dictionaries/{repo}/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesUpdateDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesUpdateDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_UpdateData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesUpdateData2 updates a dictionary record

(Record) {
*/

func (a *Client) DictionariesUpdateData2(params *DictionariesUpdateData2Params, opts ...ClientOption) (*DictionariesUpdateData2OK, error) {
	if params == nil {
		params = NewDictionariesUpdateData2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_UpdateData2",
		Method:             "PUT",
		PathPattern:        "/dictionaries/{repo}/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesUpdateData2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesUpdateData2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_UpdateData2: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesUpdateType updates custom dictionary

(Dictionary) {
*/
func (a *Client) DictionariesUpdateType(repo string, input *models.WebitelProtoDataInputDictionary, opts ...ClientOption) (*DictionariesUpdateTypeOK, error) {
	params := NewDictionariesUpdateTypeParams().WithInput(input).WithRepo(repo)
	return a.DictionariesUpdateTypeWithParams(params, opts...)
}

func (a *Client) DictionariesUpdateTypeWithParams(params *DictionariesUpdateTypeParams, opts ...ClientOption) (*DictionariesUpdateTypeOK, error) {
	if params == nil {
		params = NewDictionariesUpdateTypeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_UpdateType",
		Method:             "PATCH",
		PathPattern:        "/types/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesUpdateTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesUpdateTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_UpdateType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DictionariesUpdateType2 updates custom dictionary

(Dictionary) {
*/
func (a *Client) DictionariesUpdateType2(repo string, input *models.WebitelProtoDataInputDictionary, opts ...ClientOption) (*DictionariesUpdateType2OK, error) {
	params := NewDictionariesUpdateType2Params().WithInput(input).WithRepo(repo)
	return a.DictionariesUpdateType2WithParams(params, opts...)
}

func (a *Client) DictionariesUpdateType2WithParams(params *DictionariesUpdateType2Params, opts ...ClientOption) (*DictionariesUpdateType2OK, error) {
	if params == nil {
		params = NewDictionariesUpdateType2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "Dictionaries_UpdateType2",
		Method:             "PUT",
		PathPattern:        "/types/dictionaries/{repo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DictionariesUpdateType2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DictionariesUpdateType2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Dictionaries_UpdateType2: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}

// WithAuthInfo changes the transport on the client
func WithAuthInfo(authInfo runtime.ClientAuthInfoWriter) ClientOption {
	return func(op *runtime.ClientOperation) {
		op.AuthInfo = authInfo
	}
}
