// Code generated by go-swagger; DO NOT EDIT.

package dictionaries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewDictionariesUpdateTypeParams creates a new DictionariesUpdateTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDictionariesUpdateTypeParams() *DictionariesUpdateTypeParams {
	return &DictionariesUpdateTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDictionariesUpdateTypeParamsWithTimeout creates a new DictionariesUpdateTypeParams object
// with the ability to set a timeout on a request.
func NewDictionariesUpdateTypeParamsWithTimeout(timeout time.Duration) *DictionariesUpdateTypeParams {
	return &DictionariesUpdateTypeParams{
		timeout: timeout,
	}
}

// NewDictionariesUpdateTypeParamsWithContext creates a new DictionariesUpdateTypeParams object
// with the ability to set a context for a request.
func NewDictionariesUpdateTypeParamsWithContext(ctx context.Context) *DictionariesUpdateTypeParams {
	return &DictionariesUpdateTypeParams{
		Context: ctx,
	}
}

// NewDictionariesUpdateTypeParamsWithHTTPClient creates a new DictionariesUpdateTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDictionariesUpdateTypeParamsWithHTTPClient(client *http.Client) *DictionariesUpdateTypeParams {
	return &DictionariesUpdateTypeParams{
		HTTPClient: client,
	}
}

/*
DictionariesUpdateTypeParams contains all the parameters to send to the API endpoint

	for the dictionaries update type operation.

	Typically these are written to a http.Request.
*/
type DictionariesUpdateTypeParams struct {

	/* Input.

	   The dictionary [type] changes.
	*/
	Input *models.WebitelProtoDataInputDictionary

	/* Repo.

	   [**types.dictionaries.id**] type name, e.g.: `country`.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dictionaries update type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DictionariesUpdateTypeParams) WithDefaults() *DictionariesUpdateTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dictionaries update type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DictionariesUpdateTypeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) WithTimeout(timeout time.Duration) *DictionariesUpdateTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) WithContext(ctx context.Context) *DictionariesUpdateTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) WithHTTPClient(client *http.Client) *DictionariesUpdateTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) WithInput(input *models.WebitelProtoDataInputDictionary) *DictionariesUpdateTypeParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) SetInput(input *models.WebitelProtoDataInputDictionary) {
	o.Input = input
}

// WithRepo adds the repo to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) WithRepo(repo string) *DictionariesUpdateTypeParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the dictionaries update type params
func (o *DictionariesUpdateTypeParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *DictionariesUpdateTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
