// Code generated by go-swagger; DO NOT EDIT.

package timezones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// TimezonesUpdateTimezone2Reader is a Reader for the TimezonesUpdateTimezone2 structure.
type TimezonesUpdateTimezone2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimezonesUpdateTimezone2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTimezonesUpdateTimezone2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /contacts/{contact_id}/timezones/{etag}] Timezones_UpdateTimezone2", response, response.Code())
	}
}

// NewTimezonesUpdateTimezone2OK creates a TimezonesUpdateTimezone2OK with default headers values
func NewTimezonesUpdateTimezone2OK() *TimezonesUpdateTimezone2OK {
	return &TimezonesUpdateTimezone2OK{}
}

/*
TimezonesUpdateTimezone2OK describes a response with status code 200, with default header values.

A successful response.
*/
type TimezonesUpdateTimezone2OK struct {
	Payload *models.WebitelContactsTimezoneList
}

// IsSuccess returns true when this timezones update timezone2 Ok response has a 2xx status code
func (o *TimezonesUpdateTimezone2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this timezones update timezone2 Ok response has a 3xx status code
func (o *TimezonesUpdateTimezone2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this timezones update timezone2 Ok response has a 4xx status code
func (o *TimezonesUpdateTimezone2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this timezones update timezone2 Ok response has a 5xx status code
func (o *TimezonesUpdateTimezone2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this timezones update timezone2 Ok response a status code equal to that given
func (o *TimezonesUpdateTimezone2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the timezones update timezone2 Ok response
func (o *TimezonesUpdateTimezone2OK) Code() int {
	return 200
}

func (o *TimezonesUpdateTimezone2OK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /contacts/{contact_id}/timezones/{etag}][%d] timezonesUpdateTimezone2Ok %s", 200, payload)
}

func (o *TimezonesUpdateTimezone2OK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /contacts/{contact_id}/timezones/{etag}][%d] timezonesUpdateTimezone2Ok %s", 200, payload)
}

func (o *TimezonesUpdateTimezone2OK) GetPayload() *models.WebitelContactsTimezoneList {
	return o.Payload
}

func (o *TimezonesUpdateTimezone2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebitelContactsTimezoneList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
