// Code generated by go-swagger; DO NOT EDIT.

package working_condition_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// WorkingConditionServiceCreateWorkingConditionReader is a Reader for the WorkingConditionServiceCreateWorkingCondition structure.
type WorkingConditionServiceCreateWorkingConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkingConditionServiceCreateWorkingConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkingConditionServiceCreateWorkingConditionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewWorkingConditionServiceCreateWorkingConditionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWorkingConditionServiceCreateWorkingConditionOK creates a WorkingConditionServiceCreateWorkingConditionOK with default headers values
func NewWorkingConditionServiceCreateWorkingConditionOK() *WorkingConditionServiceCreateWorkingConditionOK {
	return &WorkingConditionServiceCreateWorkingConditionOK{}
}

/*
WorkingConditionServiceCreateWorkingConditionOK describes a response with status code 200, with default header values.

A successful response.
*/
type WorkingConditionServiceCreateWorkingConditionOK struct {
	Payload *models.WfmCreateWorkingConditionResponse
}

// IsSuccess returns true when this working condition service create working condition Ok response has a 2xx status code
func (o *WorkingConditionServiceCreateWorkingConditionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this working condition service create working condition Ok response has a 3xx status code
func (o *WorkingConditionServiceCreateWorkingConditionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this working condition service create working condition Ok response has a 4xx status code
func (o *WorkingConditionServiceCreateWorkingConditionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this working condition service create working condition Ok response has a 5xx status code
func (o *WorkingConditionServiceCreateWorkingConditionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this working condition service create working condition Ok response a status code equal to that given
func (o *WorkingConditionServiceCreateWorkingConditionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the working condition service create working condition Ok response
func (o *WorkingConditionServiceCreateWorkingConditionOK) Code() int {
	return 200
}

func (o *WorkingConditionServiceCreateWorkingConditionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /wfm/lookups/working_conditions][%d] workingConditionServiceCreateWorkingConditionOk %s", 200, payload)
}

func (o *WorkingConditionServiceCreateWorkingConditionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /wfm/lookups/working_conditions][%d] workingConditionServiceCreateWorkingConditionOk %s", 200, payload)
}

func (o *WorkingConditionServiceCreateWorkingConditionOK) GetPayload() *models.WfmCreateWorkingConditionResponse {
	return o.Payload
}

func (o *WorkingConditionServiceCreateWorkingConditionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WfmCreateWorkingConditionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkingConditionServiceCreateWorkingConditionDefault creates a WorkingConditionServiceCreateWorkingConditionDefault with default headers values
func NewWorkingConditionServiceCreateWorkingConditionDefault(code int) *WorkingConditionServiceCreateWorkingConditionDefault {
	return &WorkingConditionServiceCreateWorkingConditionDefault{
		_statusCode: code,
	}
}

/*
WorkingConditionServiceCreateWorkingConditionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type WorkingConditionServiceCreateWorkingConditionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this working condition service create working condition default response has a 2xx status code
func (o *WorkingConditionServiceCreateWorkingConditionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this working condition service create working condition default response has a 3xx status code
func (o *WorkingConditionServiceCreateWorkingConditionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this working condition service create working condition default response has a 4xx status code
func (o *WorkingConditionServiceCreateWorkingConditionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this working condition service create working condition default response has a 5xx status code
func (o *WorkingConditionServiceCreateWorkingConditionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this working condition service create working condition default response a status code equal to that given
func (o *WorkingConditionServiceCreateWorkingConditionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the working condition service create working condition default response
func (o *WorkingConditionServiceCreateWorkingConditionDefault) Code() int {
	return o._statusCode
}

func (o *WorkingConditionServiceCreateWorkingConditionDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /wfm/lookups/working_conditions][%d] WorkingConditionService_CreateWorkingCondition default %s", o._statusCode, payload)
}

func (o *WorkingConditionServiceCreateWorkingConditionDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /wfm/lookups/working_conditions][%d] WorkingConditionService_CreateWorkingCondition default %s", o._statusCode, payload)
}

func (o *WorkingConditionServiceCreateWorkingConditionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *WorkingConditionServiceCreateWorkingConditionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
