// Code generated by go-swagger; DO NOT EDIT.

package working_condition_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// WorkingConditionServiceReadWorkingConditionReader is a Reader for the WorkingConditionServiceReadWorkingCondition structure.
type WorkingConditionServiceReadWorkingConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkingConditionServiceReadWorkingConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkingConditionServiceReadWorkingConditionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewWorkingConditionServiceReadWorkingConditionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWorkingConditionServiceReadWorkingConditionOK creates a WorkingConditionServiceReadWorkingConditionOK with default headers values
func NewWorkingConditionServiceReadWorkingConditionOK() *WorkingConditionServiceReadWorkingConditionOK {
	return &WorkingConditionServiceReadWorkingConditionOK{}
}

/*
WorkingConditionServiceReadWorkingConditionOK describes a response with status code 200, with default header values.

A successful response.
*/
type WorkingConditionServiceReadWorkingConditionOK struct {
	Payload *models.WfmReadWorkingConditionResponse
}

// IsSuccess returns true when this working condition service read working condition Ok response has a 2xx status code
func (o *WorkingConditionServiceReadWorkingConditionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this working condition service read working condition Ok response has a 3xx status code
func (o *WorkingConditionServiceReadWorkingConditionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this working condition service read working condition Ok response has a 4xx status code
func (o *WorkingConditionServiceReadWorkingConditionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this working condition service read working condition Ok response has a 5xx status code
func (o *WorkingConditionServiceReadWorkingConditionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this working condition service read working condition Ok response a status code equal to that given
func (o *WorkingConditionServiceReadWorkingConditionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the working condition service read working condition Ok response
func (o *WorkingConditionServiceReadWorkingConditionOK) Code() int {
	return 200
}

func (o *WorkingConditionServiceReadWorkingConditionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /wfm/lookups/working_conditions/{id}][%d] workingConditionServiceReadWorkingConditionOk %s", 200, payload)
}

func (o *WorkingConditionServiceReadWorkingConditionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /wfm/lookups/working_conditions/{id}][%d] workingConditionServiceReadWorkingConditionOk %s", 200, payload)
}

func (o *WorkingConditionServiceReadWorkingConditionOK) GetPayload() *models.WfmReadWorkingConditionResponse {
	return o.Payload
}

func (o *WorkingConditionServiceReadWorkingConditionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WfmReadWorkingConditionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkingConditionServiceReadWorkingConditionDefault creates a WorkingConditionServiceReadWorkingConditionDefault with default headers values
func NewWorkingConditionServiceReadWorkingConditionDefault(code int) *WorkingConditionServiceReadWorkingConditionDefault {
	return &WorkingConditionServiceReadWorkingConditionDefault{
		_statusCode: code,
	}
}

/*
WorkingConditionServiceReadWorkingConditionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type WorkingConditionServiceReadWorkingConditionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this working condition service read working condition default response has a 2xx status code
func (o *WorkingConditionServiceReadWorkingConditionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this working condition service read working condition default response has a 3xx status code
func (o *WorkingConditionServiceReadWorkingConditionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this working condition service read working condition default response has a 4xx status code
func (o *WorkingConditionServiceReadWorkingConditionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this working condition service read working condition default response has a 5xx status code
func (o *WorkingConditionServiceReadWorkingConditionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this working condition service read working condition default response a status code equal to that given
func (o *WorkingConditionServiceReadWorkingConditionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the working condition service read working condition default response
func (o *WorkingConditionServiceReadWorkingConditionDefault) Code() int {
	return o._statusCode
}

func (o *WorkingConditionServiceReadWorkingConditionDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /wfm/lookups/working_conditions/{id}][%d] WorkingConditionService_ReadWorkingCondition default %s", o._statusCode, payload)
}

func (o *WorkingConditionServiceReadWorkingConditionDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /wfm/lookups/working_conditions/{id}][%d] WorkingConditionService_ReadWorkingCondition default %s", o._statusCode, payload)
}

func (o *WorkingConditionServiceReadWorkingConditionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *WorkingConditionServiceReadWorkingConditionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
