// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewUsersUpdateUser2Params creates a new UsersUpdateUser2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUsersUpdateUser2Params() *UsersUpdateUser2Params {
	return &UsersUpdateUser2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewUsersUpdateUser2ParamsWithTimeout creates a new UsersUpdateUser2Params object
// with the ability to set a timeout on a request.
func NewUsersUpdateUser2ParamsWithTimeout(timeout time.Duration) *UsersUpdateUser2Params {
	return &UsersUpdateUser2Params{
		timeout: timeout,
	}
}

// NewUsersUpdateUser2ParamsWithContext creates a new UsersUpdateUser2Params object
// with the ability to set a context for a request.
func NewUsersUpdateUser2ParamsWithContext(ctx context.Context) *UsersUpdateUser2Params {
	return &UsersUpdateUser2Params{
		Context: ctx,
	}
}

// NewUsersUpdateUser2ParamsWithHTTPClient creates a new UsersUpdateUser2Params object
// with the ability to set a custom HTTPClient for a request.
func NewUsersUpdateUser2ParamsWithHTTPClient(client *http.Client) *UsersUpdateUser2Params {
	return &UsersUpdateUser2Params{
		HTTPClient: client,
	}
}

/*
UsersUpdateUser2Params contains all the parameters to send to the API endpoint

	for the users update user2 operation.

	Typically these are written to a http.Request.
*/
type UsersUpdateUser2Params struct {

	/* Fields.

	   PATCH: partial update
	*/
	Fields []string

	/* User.

	   body: modifications/changes
	*/
	User *models.UsersUpdateUser2ParamsBody

	/* UserID.

	   Object ID

	   Format: int64
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the users update user2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersUpdateUser2Params) WithDefaults() *UsersUpdateUser2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the users update user2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersUpdateUser2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the users update user2 params
func (o *UsersUpdateUser2Params) WithTimeout(timeout time.Duration) *UsersUpdateUser2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users update user2 params
func (o *UsersUpdateUser2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users update user2 params
func (o *UsersUpdateUser2Params) WithContext(ctx context.Context) *UsersUpdateUser2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users update user2 params
func (o *UsersUpdateUser2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users update user2 params
func (o *UsersUpdateUser2Params) WithHTTPClient(client *http.Client) *UsersUpdateUser2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users update user2 params
func (o *UsersUpdateUser2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the users update user2 params
func (o *UsersUpdateUser2Params) WithFields(fields []string) *UsersUpdateUser2Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the users update user2 params
func (o *UsersUpdateUser2Params) SetFields(fields []string) {
	o.Fields = fields
}

// WithUser adds the user to the users update user2 params
func (o *UsersUpdateUser2Params) WithUser(user *models.UsersUpdateUser2ParamsBody) *UsersUpdateUser2Params {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the users update user2 params
func (o *UsersUpdateUser2Params) SetUser(user *models.UsersUpdateUser2ParamsBody) {
	o.User = user
}

// WithUserID adds the userID to the users update user2 params
func (o *UsersUpdateUser2Params) WithUserID(userID string) *UsersUpdateUser2Params {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the users update user2 params
func (o *UsersUpdateUser2Params) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UsersUpdateUser2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}
	if o.User != nil {
		if err := r.SetBodyParam(o.User); err != nil {
			return err
		}
	}

	// path param user.id
	if err := r.SetPathParam("user.id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamUsersUpdateUser2 binds the parameter fields
func (o *UsersUpdateUser2Params) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldsIS := swag.JoinByFormat(fieldsIC, "multi")

	return fieldsIS
}
