// Code generated by go-swagger; DO NOT EDIT.

package working_schedule_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams creates a new WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams() *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	return &WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParamsWithTimeout creates a new WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams object
// with the ability to set a timeout on a request.
func NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParamsWithTimeout(timeout time.Duration) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	return &WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams{
		timeout: timeout,
	}
}

// NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParamsWithContext creates a new WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams object
// with the ability to set a context for a request.
func NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParamsWithContext(ctx context.Context) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	return &WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams{
		Context: ctx,
	}
}

// NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParamsWithHTTPClient creates a new WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams object
// with the ability to set a custom HTTPClient for a request.
func NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParamsWithHTTPClient(client *http.Client) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	return &WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams{
		HTTPClient: client,
	}
}

/*
WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams contains all the parameters to send to the API endpoint

	for the working schedule service update working schedule remove agent operation.

	Typically these are written to a http.Request.
*/
type WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams struct {

	// AgentID.
	//
	// Format: int64
	AgentID string

	// ID.
	//
	// Format: int64
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the working schedule service update working schedule remove agent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WithDefaults() *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the working schedule service update working schedule remove agent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WithTimeout(timeout time.Duration) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WithContext(ctx context.Context) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WithHTTPClient(client *http.Client) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentID adds the agentID to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WithAgentID(agentID string) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	o.SetAgentID(agentID)
	return o
}

// SetAgentID adds the agentId to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) SetAgentID(agentID string) {
	o.AgentID = agentID
}

// WithID adds the id to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WithID(id string) *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the working schedule service update working schedule remove agent params
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent_id
	if err := r.SetPathParam("agent_id", o.AgentID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
