// Code generated by go-swagger; DO NOT EDIT.

package working_schedule_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// New creates a new working schedule service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for working schedule service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	WorkingScheduleServiceCreateWorkingSchedule(body *models.WfmCreateWorkingScheduleRequest, opts ...ClientOption) (*WorkingScheduleServiceCreateWorkingScheduleOK, error)
	WorkingScheduleServiceCreateWorkingScheduleWithParams(params *WorkingScheduleServiceCreateWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceCreateWorkingScheduleOK, error)

	WorkingScheduleServiceDeleteWorkingSchedule(id string, opts ...ClientOption) (*WorkingScheduleServiceDeleteWorkingScheduleOK, error)
	WorkingScheduleServiceDeleteWorkingScheduleWithParams(params *WorkingScheduleServiceDeleteWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceDeleteWorkingScheduleOK, error)

	WorkingScheduleServiceReadWorkingSchedule(params *WorkingScheduleServiceReadWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceReadWorkingScheduleOK, error)

	WorkingScheduleServiceReadWorkingScheduleForecast(params *WorkingScheduleServiceReadWorkingScheduleForecastParams, opts ...ClientOption) (*WorkingScheduleServiceReadWorkingScheduleForecastOK, error)

	WorkingScheduleServiceSearchWorkingSchedule(params *WorkingScheduleServiceSearchWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceSearchWorkingScheduleOK, error)

	WorkingScheduleServiceUpdateWorkingSchedule(itemID string, body *models.WorkingScheduleServiceUpdateWorkingScheduleParamsBody, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleOK, error)
	WorkingScheduleServiceUpdateWorkingScheduleWithParams(params *WorkingScheduleServiceUpdateWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleOK, error)

	WorkingScheduleServiceUpdateWorkingScheduleAddAgents(id string, body *models.WorkingScheduleServiceUpdateWorkingScheduleAddAgentsParamsBody, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleAddAgentsOK, error)
	WorkingScheduleServiceUpdateWorkingScheduleAddAgentsWithParams(params *WorkingScheduleServiceUpdateWorkingScheduleAddAgentsParams, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleAddAgentsOK, error)

	WorkingScheduleServiceUpdateWorkingScheduleRemoveAgent(id string, agentID string, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentOK, error)
	WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentWithParams(params *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
WorkingScheduleServiceCreateWorkingSchedule working schedule service create working schedule API
*/
func (a *Client) WorkingScheduleServiceCreateWorkingSchedule(body *models.WfmCreateWorkingScheduleRequest, opts ...ClientOption) (*WorkingScheduleServiceCreateWorkingScheduleOK, error) {
	params := NewWorkingScheduleServiceCreateWorkingScheduleParams().WithBody(body)
	return a.WorkingScheduleServiceCreateWorkingScheduleWithParams(params, opts...)
}

func (a *Client) WorkingScheduleServiceCreateWorkingScheduleWithParams(params *WorkingScheduleServiceCreateWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceCreateWorkingScheduleOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceCreateWorkingScheduleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_CreateWorkingSchedule",
		Method:             "POST",
		PathPattern:        "/wfm/lookups/working_schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceCreateWorkingScheduleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceCreateWorkingScheduleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_CreateWorkingSchedule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceDeleteWorkingSchedule working schedule service delete working schedule API
*/
func (a *Client) WorkingScheduleServiceDeleteWorkingSchedule(id string, opts ...ClientOption) (*WorkingScheduleServiceDeleteWorkingScheduleOK, error) {
	params := NewWorkingScheduleServiceDeleteWorkingScheduleParams().WithID(id)
	return a.WorkingScheduleServiceDeleteWorkingScheduleWithParams(params, opts...)
}

func (a *Client) WorkingScheduleServiceDeleteWorkingScheduleWithParams(params *WorkingScheduleServiceDeleteWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceDeleteWorkingScheduleOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceDeleteWorkingScheduleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_DeleteWorkingSchedule",
		Method:             "DELETE",
		PathPattern:        "/wfm/lookups/working_schedules/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceDeleteWorkingScheduleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceDeleteWorkingScheduleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_DeleteWorkingSchedule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceReadWorkingSchedule working schedule service read working schedule API
*/

func (a *Client) WorkingScheduleServiceReadWorkingSchedule(params *WorkingScheduleServiceReadWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceReadWorkingScheduleOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceReadWorkingScheduleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_ReadWorkingSchedule",
		Method:             "GET",
		PathPattern:        "/wfm/lookups/working_schedules/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceReadWorkingScheduleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceReadWorkingScheduleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_ReadWorkingSchedule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceReadWorkingScheduleForecast working schedule service read working schedule forecast API
*/

func (a *Client) WorkingScheduleServiceReadWorkingScheduleForecast(params *WorkingScheduleServiceReadWorkingScheduleForecastParams, opts ...ClientOption) (*WorkingScheduleServiceReadWorkingScheduleForecastOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceReadWorkingScheduleForecastParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_ReadWorkingScheduleForecast",
		Method:             "GET",
		PathPattern:        "/wfm/lookups/working_schedules/{id}/forecast",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceReadWorkingScheduleForecastReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceReadWorkingScheduleForecastOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_ReadWorkingScheduleForecast: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceSearchWorkingSchedule working schedule service search working schedule API
*/

func (a *Client) WorkingScheduleServiceSearchWorkingSchedule(params *WorkingScheduleServiceSearchWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceSearchWorkingScheduleOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceSearchWorkingScheduleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_SearchWorkingSchedule",
		Method:             "GET",
		PathPattern:        "/wfm/lookups/working_schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceSearchWorkingScheduleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceSearchWorkingScheduleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_SearchWorkingSchedule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceUpdateWorkingSchedule working schedule service update working schedule API
*/
func (a *Client) WorkingScheduleServiceUpdateWorkingSchedule(itemID string, body *models.WorkingScheduleServiceUpdateWorkingScheduleParamsBody, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleOK, error) {
	params := NewWorkingScheduleServiceUpdateWorkingScheduleParams().WithBody(body).WithItemID(itemID)
	return a.WorkingScheduleServiceUpdateWorkingScheduleWithParams(params, opts...)
}

func (a *Client) WorkingScheduleServiceUpdateWorkingScheduleWithParams(params *WorkingScheduleServiceUpdateWorkingScheduleParams, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceUpdateWorkingScheduleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_UpdateWorkingSchedule",
		Method:             "PUT",
		PathPattern:        "/wfm/lookups/working_schedules/{item.id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceUpdateWorkingScheduleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceUpdateWorkingScheduleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_UpdateWorkingSchedule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceUpdateWorkingScheduleAddAgents working schedule service update working schedule add agents API
*/
func (a *Client) WorkingScheduleServiceUpdateWorkingScheduleAddAgents(id string, body *models.WorkingScheduleServiceUpdateWorkingScheduleAddAgentsParamsBody, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleAddAgentsOK, error) {
	params := NewWorkingScheduleServiceUpdateWorkingScheduleAddAgentsParams().WithBody(body).WithID(id)
	return a.WorkingScheduleServiceUpdateWorkingScheduleAddAgentsWithParams(params, opts...)
}

func (a *Client) WorkingScheduleServiceUpdateWorkingScheduleAddAgentsWithParams(params *WorkingScheduleServiceUpdateWorkingScheduleAddAgentsParams, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleAddAgentsOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceUpdateWorkingScheduleAddAgentsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_UpdateWorkingScheduleAddAgents",
		Method:             "POST",
		PathPattern:        "/wfm/lookups/working_schedules/{id}/agents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceUpdateWorkingScheduleAddAgentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceUpdateWorkingScheduleAddAgentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_UpdateWorkingScheduleAddAgents: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
WorkingScheduleServiceUpdateWorkingScheduleRemoveAgent working schedule service update working schedule remove agent API
*/
func (a *Client) WorkingScheduleServiceUpdateWorkingScheduleRemoveAgent(id string, agentID string, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentOK, error) {
	params := NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams().WithAgentID(agentID).WithID(id)
	return a.WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentWithParams(params, opts...)
}

func (a *Client) WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentWithParams(params *WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams, opts ...ClientOption) (*WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentOK, error) {
	if params == nil {
		params = NewWorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "WorkingScheduleService_UpdateWorkingScheduleRemoveAgent",
		Method:             "DELETE",
		PathPattern:        "/wfm/lookups/working_schedules/{id}/agents/{agent_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for WorkingScheduleService_UpdateWorkingScheduleRemoveAgent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}

// WithAuthInfo changes the transport on the client
func WithAuthInfo(authInfo runtime.ClientAuthInfoWriter) ClientOption {
	return func(op *runtime.ClientOperation) {
		op.AuthInfo = authInfo
	}
}
