// Code generated by go-swagger; DO NOT EDIT.

package case_communications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// UnlinkCommunicationReader is a Reader for the UnlinkCommunication structure.
type UnlinkCommunicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnlinkCommunicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnlinkCommunicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUnlinkCommunicationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUnlinkCommunicationOK creates a UnlinkCommunicationOK with default headers values
func NewUnlinkCommunicationOK() *UnlinkCommunicationOK {
	return &UnlinkCommunicationOK{}
}

/*
UnlinkCommunicationOK describes a response with status code 200, with default header values.

A successful response.
*/
type UnlinkCommunicationOK struct {
	Payload *models.CasesUnlinkCommunicationResponse
}

// IsSuccess returns true when this unlink communication Ok response has a 2xx status code
func (o *UnlinkCommunicationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this unlink communication Ok response has a 3xx status code
func (o *UnlinkCommunicationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlink communication Ok response has a 4xx status code
func (o *UnlinkCommunicationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this unlink communication Ok response has a 5xx status code
func (o *UnlinkCommunicationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this unlink communication Ok response a status code equal to that given
func (o *UnlinkCommunicationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the unlink communication Ok response
func (o *UnlinkCommunicationOK) Code() int {
	return 200
}

func (o *UnlinkCommunicationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /cases/{case_etag}/communication/{id}][%d] unlinkCommunicationOk %s", 200, payload)
}

func (o *UnlinkCommunicationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /cases/{case_etag}/communication/{id}][%d] unlinkCommunicationOk %s", 200, payload)
}

func (o *UnlinkCommunicationOK) GetPayload() *models.CasesUnlinkCommunicationResponse {
	return o.Payload
}

func (o *UnlinkCommunicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CasesUnlinkCommunicationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnlinkCommunicationDefault creates a UnlinkCommunicationDefault with default headers values
func NewUnlinkCommunicationDefault(code int) *UnlinkCommunicationDefault {
	return &UnlinkCommunicationDefault{
		_statusCode: code,
	}
}

/*
UnlinkCommunicationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UnlinkCommunicationDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this unlink communication default response has a 2xx status code
func (o *UnlinkCommunicationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this unlink communication default response has a 3xx status code
func (o *UnlinkCommunicationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this unlink communication default response has a 4xx status code
func (o *UnlinkCommunicationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this unlink communication default response has a 5xx status code
func (o *UnlinkCommunicationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this unlink communication default response a status code equal to that given
func (o *UnlinkCommunicationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the unlink communication default response
func (o *UnlinkCommunicationDefault) Code() int {
	return o._statusCode
}

func (o *UnlinkCommunicationDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /cases/{case_etag}/communication/{id}][%d] UnlinkCommunication default %s", o._statusCode, payload)
}

func (o *UnlinkCommunicationDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /cases/{case_etag}/communication/{id}][%d] UnlinkCommunication default %s", o._statusCode, payload)
}

func (o *UnlinkCommunicationDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *UnlinkCommunicationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
