// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTypesSearchParams creates a new TypesSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTypesSearchParams() *TypesSearchParams {
	return &TypesSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTypesSearchParamsWithTimeout creates a new TypesSearchParams object
// with the ability to set a timeout on a request.
func NewTypesSearchParamsWithTimeout(timeout time.Duration) *TypesSearchParams {
	return &TypesSearchParams{
		timeout: timeout,
	}
}

// NewTypesSearchParamsWithContext creates a new TypesSearchParams object
// with the ability to set a context for a request.
func NewTypesSearchParamsWithContext(ctx context.Context) *TypesSearchParams {
	return &TypesSearchParams{
		Context: ctx,
	}
}

// NewTypesSearchParamsWithHTTPClient creates a new TypesSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewTypesSearchParamsWithHTTPClient(client *http.Client) *TypesSearchParams {
	return &TypesSearchParams{
		HTTPClient: client,
	}
}

/*
TypesSearchParams contains all the parameters to send to the API endpoint

	for the types search operation.

	Typically these are written to a http.Request.
*/
type TypesSearchParams struct {

	/* Administered.

	   [NOT] Administer access control only
	*/
	Administered *bool

	/* Extendable.

	   [NOT] Extend[able] types only.
	*/
	Extendable *bool

	/* Extended.

	   [NOT] Extend[ed] types only.
	*/
	Extended *bool

	/* Fields.

	     Fields [Q]uery to build result dataset record.
	```
	fields ::= field [ *( "," field ) ]
	field  ::= name [ *( func ) ] [ inner ]
	inner  ::= "{" fields "}"
	funcs  ::= *( func )
	func   ::= "." name "(" [ args ] ")"
	name   ::= ALPHA / DIGIT / USCORE

	ALPHA    = %x41-5A / %x61-7A  ; "A"-"Z" / "a"-"z"
	DIGIT    = %x30-39            ; "0"-"9"
	USCORE   = %x5F ; underscore  ; "_"
	```
	*/
	Fields []string

	/* ID.

	   `types.id`
	*/
	ID *string

	/* Name.

	   `types.name`
	*/
	Name *string

	/* Page.

	     Page number of result set of records.
	Default: 1.

	     Format: int32
	*/
	Page *int32

	/* Path.

	   `types.path`
	*/
	Path *string

	/* Q.

	     Search term:
	`?` - matches any character
	`*` - matches 0 or more characters
	e.g.: name,emails{type},labels etc...
	*/
	Q *string

	/* Readonly.

	   [NOT] [ system / custom ] types only
	*/
	Readonly *bool

	/* Repo.

	   `types.repo`
	*/
	Repo *string

	/* Size.

	     Number of result records (per page).
	Default: 16.

	     Format: int32
	*/
	Size *int32

	/* Sort.

	     Sort result dataset of records by fields.
	```
	sort ::= *( ORDER name )

	ORDER  = ASC / DESC
	DESC   = "-" / "!"
	ASC    = [ "+" ]   ; Default
	```

	Fields available

	- `id`(seq)
	- `domain`{name}
	- `created_at`
	- `created_by`{name}
	- `updated_at`
	- `updated_by`{name}

	Use ?fields=`field.sort()` option to sort Edge fields.
	*/
	Sort []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the types search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TypesSearchParams) WithDefaults() *TypesSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the types search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TypesSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the types search params
func (o *TypesSearchParams) WithTimeout(timeout time.Duration) *TypesSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the types search params
func (o *TypesSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the types search params
func (o *TypesSearchParams) WithContext(ctx context.Context) *TypesSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the types search params
func (o *TypesSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the types search params
func (o *TypesSearchParams) WithHTTPClient(client *http.Client) *TypesSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the types search params
func (o *TypesSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAdministered adds the administered to the types search params
func (o *TypesSearchParams) WithAdministered(administered *bool) *TypesSearchParams {
	o.SetAdministered(administered)
	return o
}

// SetAdministered adds the administered to the types search params
func (o *TypesSearchParams) SetAdministered(administered *bool) {
	o.Administered = administered
}

// WithExtendable adds the extendable to the types search params
func (o *TypesSearchParams) WithExtendable(extendable *bool) *TypesSearchParams {
	o.SetExtendable(extendable)
	return o
}

// SetExtendable adds the extendable to the types search params
func (o *TypesSearchParams) SetExtendable(extendable *bool) {
	o.Extendable = extendable
}

// WithExtended adds the extended to the types search params
func (o *TypesSearchParams) WithExtended(extended *bool) *TypesSearchParams {
	o.SetExtended(extended)
	return o
}

// SetExtended adds the extended to the types search params
func (o *TypesSearchParams) SetExtended(extended *bool) {
	o.Extended = extended
}

// WithFields adds the fields to the types search params
func (o *TypesSearchParams) WithFields(fields []string) *TypesSearchParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the types search params
func (o *TypesSearchParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithID adds the id to the types search params
func (o *TypesSearchParams) WithID(id *string) *TypesSearchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the types search params
func (o *TypesSearchParams) SetID(id *string) {
	o.ID = id
}

// WithName adds the name to the types search params
func (o *TypesSearchParams) WithName(name *string) *TypesSearchParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the types search params
func (o *TypesSearchParams) SetName(name *string) {
	o.Name = name
}

// WithPage adds the page to the types search params
func (o *TypesSearchParams) WithPage(page *int32) *TypesSearchParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the types search params
func (o *TypesSearchParams) SetPage(page *int32) {
	o.Page = page
}

// WithPath adds the path to the types search params
func (o *TypesSearchParams) WithPath(path *string) *TypesSearchParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the types search params
func (o *TypesSearchParams) SetPath(path *string) {
	o.Path = path
}

// WithQ adds the q to the types search params
func (o *TypesSearchParams) WithQ(q *string) *TypesSearchParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the types search params
func (o *TypesSearchParams) SetQ(q *string) {
	o.Q = q
}

// WithReadonly adds the readonly to the types search params
func (o *TypesSearchParams) WithReadonly(readonly *bool) *TypesSearchParams {
	o.SetReadonly(readonly)
	return o
}

// SetReadonly adds the readonly to the types search params
func (o *TypesSearchParams) SetReadonly(readonly *bool) {
	o.Readonly = readonly
}

// WithRepo adds the repo to the types search params
func (o *TypesSearchParams) WithRepo(repo *string) *TypesSearchParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the types search params
func (o *TypesSearchParams) SetRepo(repo *string) {
	o.Repo = repo
}

// WithSize adds the size to the types search params
func (o *TypesSearchParams) WithSize(size *int32) *TypesSearchParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the types search params
func (o *TypesSearchParams) SetSize(size *int32) {
	o.Size = size
}

// WithSort adds the sort to the types search params
func (o *TypesSearchParams) WithSort(sort []string) *TypesSearchParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the types search params
func (o *TypesSearchParams) SetSort(sort []string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *TypesSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Administered != nil {

		// query param administered
		var qrAdministered bool

		if o.Administered != nil {
			qrAdministered = *o.Administered
		}
		qAdministered := swag.FormatBool(qrAdministered)
		if qAdministered != "" {

			if err := r.SetQueryParam("administered", qAdministered); err != nil {
				return err
			}
		}
	}

	if o.Extendable != nil {

		// query param extendable
		var qrExtendable bool

		if o.Extendable != nil {
			qrExtendable = *o.Extendable
		}
		qExtendable := swag.FormatBool(qrExtendable)
		if qExtendable != "" {

			if err := r.SetQueryParam("extendable", qExtendable); err != nil {
				return err
			}
		}
	}

	if o.Extended != nil {

		// query param extended
		var qrExtended bool

		if o.Extended != nil {
			qrExtended = *o.Extended
		}
		qExtended := swag.FormatBool(qrExtended)
		if qExtended != "" {

			if err := r.SetQueryParam("extended", qExtended); err != nil {
				return err
			}
		}
	}

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int32

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Path != nil {

		// query param path
		var qrPath string

		if o.Path != nil {
			qrPath = *o.Path
		}
		qPath := qrPath
		if qPath != "" {

			if err := r.SetQueryParam("path", qPath); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if o.Readonly != nil {

		// query param readonly
		var qrReadonly bool

		if o.Readonly != nil {
			qrReadonly = *o.Readonly
		}
		qReadonly := swag.FormatBool(qrReadonly)
		if qReadonly != "" {

			if err := r.SetQueryParam("readonly", qReadonly); err != nil {
				return err
			}
		}
	}

	if o.Repo != nil {

		// query param repo
		var qrRepo string

		if o.Repo != nil {
			qrRepo = *o.Repo
		}
		qRepo := qrRepo
		if qRepo != "" {

			if err := r.SetQueryParam("repo", qRepo); err != nil {
				return err
			}
		}
	}

	if o.Size != nil {

		// query param size
		var qrSize int32

		if o.Size != nil {
			qrSize = *o.Size
		}
		qSize := swag.FormatInt32(qrSize)
		if qSize != "" {

			if err := r.SetQueryParam("size", qSize); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// binding items for sort
		joinedSort := o.bindParamSort(reg)

		// query array param sort
		if err := r.SetQueryParam("sort", joinedSort...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamTypesSearch binds the parameter fields
func (o *TypesSearchParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldsIS := swag.JoinByFormat(fieldsIC, "multi")

	return fieldsIS
}

// bindParamTypesSearch binds the parameter sort
func (o *TypesSearchParams) bindParamSort(formats strfmt.Registry) []string {
	sortIR := o.Sort

	var sortIC []string
	for _, sortIIR := range sortIR { // explode []string

		sortIIV := sortIIR // string as string
		sortIC = append(sortIC, sortIIV)
	}

	// items.CollectionFormat: "multi"
	sortIS := swag.JoinByFormat(sortIC, "multi")

	return sortIS
}
