// Code generated by go-swagger; DO NOT EDIT.

package case_comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new case comments API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for case comments API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteComment(params *DeleteCommentParams, opts ...ClientOption) (*DeleteCommentOK, error)

	ListComments(params *ListCommentsParams, opts ...ClientOption) (*ListCommentsOK, error)

	LocateComment(params *LocateCommentParams, opts ...ClientOption) (*LocateCommentOK, error)

	PublishComment(params *PublishCommentParams, opts ...ClientOption) (*PublishCommentOK, error)

	UpdateComment(params *UpdateCommentParams, opts ...ClientOption) (*UpdateCommentOK, error)

	UpdateComment2(params *UpdateComment2Params, opts ...ClientOption) (*UpdateComment2OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteComment deletes a specific comment by its etag
*/

func (a *Client) DeleteComment(params *DeleteCommentParams, opts ...ClientOption) (*DeleteCommentOK, error) {
	if params == nil {
		params = NewDeleteCommentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteComment",
		Method:             "DELETE",
		PathPattern:        "/cases/comments/{etag}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteCommentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteCommentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteCommentDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListComments retrieves a list of comments associated with a specific case
*/

func (a *Client) ListComments(params *ListCommentsParams, opts ...ClientOption) (*ListCommentsOK, error) {
	if params == nil {
		params = NewListCommentsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListComments",
		Method:             "GET",
		PathPattern:        "/cases/{case_etag}/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListCommentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListCommentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListCommentsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
LocateComment retrieves a specific comment by its etag
*/

func (a *Client) LocateComment(params *LocateCommentParams, opts ...ClientOption) (*LocateCommentOK, error) {
	if params == nil {
		params = NewLocateCommentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "LocateComment",
		Method:             "GET",
		PathPattern:        "/cases/comments/{etag}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LocateCommentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*LocateCommentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*LocateCommentDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PublishComment publishes comment into a specific case
*/

func (a *Client) PublishComment(params *PublishCommentParams, opts ...ClientOption) (*PublishCommentOK, error) {
	if params == nil {
		params = NewPublishCommentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PublishComment",
		Method:             "POST",
		PathPattern:        "/cases/{case_etag}/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PublishCommentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PublishCommentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PublishCommentDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateComment updates a specific comment by its etag
*/

func (a *Client) UpdateComment(params *UpdateCommentParams, opts ...ClientOption) (*UpdateCommentOK, error) {
	if params == nil {
		params = NewUpdateCommentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateComment",
		Method:             "PUT",
		PathPattern:        "/cases/comments/{input.etag}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateCommentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateCommentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateCommentDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateComment2 updates a specific comment by its etag
*/

func (a *Client) UpdateComment2(params *UpdateComment2Params, opts ...ClientOption) (*UpdateComment2OK, error) {
	if params == nil {
		params = NewUpdateComment2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateComment2",
		Method:             "PATCH",
		PathPattern:        "/cases/comments/{input.etag}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateComment2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		if opt != nil {
			opt(op)
		}
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateComment2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateComment2Default)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}

// WithAuthInfo changes the transport on the client
func WithAuthInfo(authInfo runtime.ClientAuthInfoWriter) ClientOption {
	return func(op *runtime.ClientOperation) {
		op.AuthInfo = authInfo
	}
}
