// Code generated by go-swagger; DO NOT EDIT.

package file_transcript_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// DeleteFileTranscriptReader is a Reader for the DeleteFileTranscript structure.
type DeleteFileTranscriptReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFileTranscriptReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFileTranscriptOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /storage/transcript_file] DeleteFileTranscript", response, response.Code())
	}
}

// NewDeleteFileTranscriptOK creates a DeleteFileTranscriptOK with default headers values
func NewDeleteFileTranscriptOK() *DeleteFileTranscriptOK {
	return &DeleteFileTranscriptOK{}
}

/*
DeleteFileTranscriptOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeleteFileTranscriptOK struct {
	Payload *models.StorageDeleteFileTranscriptResponse
}

// IsSuccess returns true when this delete file transcript Ok response has a 2xx status code
func (o *DeleteFileTranscriptOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete file transcript Ok response has a 3xx status code
func (o *DeleteFileTranscriptOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete file transcript Ok response has a 4xx status code
func (o *DeleteFileTranscriptOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete file transcript Ok response has a 5xx status code
func (o *DeleteFileTranscriptOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete file transcript Ok response a status code equal to that given
func (o *DeleteFileTranscriptOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete file transcript Ok response
func (o *DeleteFileTranscriptOK) Code() int {
	return 200
}

func (o *DeleteFileTranscriptOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /storage/transcript_file][%d] deleteFileTranscriptOk %s", 200, payload)
}

func (o *DeleteFileTranscriptOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /storage/transcript_file][%d] deleteFileTranscriptOk %s", 200, payload)
}

func (o *DeleteFileTranscriptOK) GetPayload() *models.StorageDeleteFileTranscriptResponse {
	return o.Payload
}

func (o *DeleteFileTranscriptOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageDeleteFileTranscriptResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
