// Code generated by go-swagger; DO NOT EDIT.

package agent_chats_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// AgentChatsServiceGetAgentChatsReader is a Reader for the AgentChatsServiceGetAgentChats structure.
type AgentChatsServiceGetAgentChatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentChatsServiceGetAgentChatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAgentChatsServiceGetAgentChatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /agent/chats] AgentChatsService_GetAgentChats", response, response.Code())
	}
}

// NewAgentChatsServiceGetAgentChatsOK creates a AgentChatsServiceGetAgentChatsOK with default headers values
func NewAgentChatsServiceGetAgentChatsOK() *AgentChatsServiceGetAgentChatsOK {
	return &AgentChatsServiceGetAgentChatsOK{}
}

/*
AgentChatsServiceGetAgentChatsOK describes a response with status code 200, with default header values.

A successful response.
*/
type AgentChatsServiceGetAgentChatsOK struct {
	Payload *models.WebitelChatGetAgentChatsResponse
}

// IsSuccess returns true when this agent chats service get agent chats Ok response has a 2xx status code
func (o *AgentChatsServiceGetAgentChatsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this agent chats service get agent chats Ok response has a 3xx status code
func (o *AgentChatsServiceGetAgentChatsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent chats service get agent chats Ok response has a 4xx status code
func (o *AgentChatsServiceGetAgentChatsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent chats service get agent chats Ok response has a 5xx status code
func (o *AgentChatsServiceGetAgentChatsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this agent chats service get agent chats Ok response a status code equal to that given
func (o *AgentChatsServiceGetAgentChatsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the agent chats service get agent chats Ok response
func (o *AgentChatsServiceGetAgentChatsOK) Code() int {
	return 200
}

func (o *AgentChatsServiceGetAgentChatsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agent/chats][%d] agentChatsServiceGetAgentChatsOk %s", 200, payload)
}

func (o *AgentChatsServiceGetAgentChatsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agent/chats][%d] agentChatsServiceGetAgentChatsOk %s", 200, payload)
}

func (o *AgentChatsServiceGetAgentChatsOK) GetPayload() *models.WebitelChatGetAgentChatsResponse {
	return o.Payload
}

func (o *AgentChatsServiceGetAgentChatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebitelChatGetAgentChatsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
