// Code generated by go-swagger; DO NOT EDIT.

package dynamic_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// DynamicConditionsUpdateConditionReader is a Reader for the DynamicConditionsUpdateCondition structure.
type DynamicConditionsUpdateConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DynamicConditionsUpdateConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDynamicConditionsUpdateConditionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /contacts/groups/conditions/{id}] DynamicConditions_UpdateCondition", response, response.Code())
	}
}

// NewDynamicConditionsUpdateConditionOK creates a DynamicConditionsUpdateConditionOK with default headers values
func NewDynamicConditionsUpdateConditionOK() *DynamicConditionsUpdateConditionOK {
	return &DynamicConditionsUpdateConditionOK{}
}

/*
DynamicConditionsUpdateConditionOK describes a response with status code 200, with default header values.

A successful response.
*/
type DynamicConditionsUpdateConditionOK struct {
	Payload *models.WebitelContactsCondition
}

// IsSuccess returns true when this dynamic conditions update condition Ok response has a 2xx status code
func (o *DynamicConditionsUpdateConditionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dynamic conditions update condition Ok response has a 3xx status code
func (o *DynamicConditionsUpdateConditionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dynamic conditions update condition Ok response has a 4xx status code
func (o *DynamicConditionsUpdateConditionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dynamic conditions update condition Ok response has a 5xx status code
func (o *DynamicConditionsUpdateConditionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dynamic conditions update condition Ok response a status code equal to that given
func (o *DynamicConditionsUpdateConditionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dynamic conditions update condition Ok response
func (o *DynamicConditionsUpdateConditionOK) Code() int {
	return 200
}

func (o *DynamicConditionsUpdateConditionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /contacts/groups/conditions/{id}][%d] dynamicConditionsUpdateConditionOk %s", 200, payload)
}

func (o *DynamicConditionsUpdateConditionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /contacts/groups/conditions/{id}][%d] dynamicConditionsUpdateConditionOk %s", 200, payload)
}

func (o *DynamicConditionsUpdateConditionOK) GetPayload() *models.WebitelContactsCondition {
	return o.Payload
}

func (o *DynamicConditionsUpdateConditionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebitelContactsCondition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
