// Code generated by go-swagger; DO NOT EDIT.

package audit_form_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// SearchAuditRateReader is a Reader for the SearchAuditRate structure.
type SearchAuditRateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchAuditRateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchAuditRateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSearchAuditRateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSearchAuditRateOK creates a SearchAuditRateOK with default headers values
func NewSearchAuditRateOK() *SearchAuditRateOK {
	return &SearchAuditRateOK{}
}

/*
SearchAuditRateOK describes a response with status code 200, with default header values.

A successful response.
*/
type SearchAuditRateOK struct {
	Payload *models.EngineListAuditRate
}

// IsSuccess returns true when this search audit rate Ok response has a 2xx status code
func (o *SearchAuditRateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search audit rate Ok response has a 3xx status code
func (o *SearchAuditRateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search audit rate Ok response has a 4xx status code
func (o *SearchAuditRateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search audit rate Ok response has a 5xx status code
func (o *SearchAuditRateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search audit rate Ok response a status code equal to that given
func (o *SearchAuditRateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search audit rate Ok response
func (o *SearchAuditRateOK) Code() int {
	return 200
}

func (o *SearchAuditRateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/audit/forms/{form_id}/rate][%d] searchAuditRateOk %s", 200, payload)
}

func (o *SearchAuditRateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/audit/forms/{form_id}/rate][%d] searchAuditRateOk %s", 200, payload)
}

func (o *SearchAuditRateOK) GetPayload() *models.EngineListAuditRate {
	return o.Payload
}

func (o *SearchAuditRateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineListAuditRate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAuditRateDefault creates a SearchAuditRateDefault with default headers values
func NewSearchAuditRateDefault(code int) *SearchAuditRateDefault {
	return &SearchAuditRateDefault{
		_statusCode: code,
	}
}

/*
SearchAuditRateDefault describes a response with status code -1, with default header values.

Server error
*/
type SearchAuditRateDefault struct {
	_statusCode int

	Payload *models.EngineAPIError
}

// IsSuccess returns true when this search audit rate default response has a 2xx status code
func (o *SearchAuditRateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search audit rate default response has a 3xx status code
func (o *SearchAuditRateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search audit rate default response has a 4xx status code
func (o *SearchAuditRateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search audit rate default response has a 5xx status code
func (o *SearchAuditRateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search audit rate default response a status code equal to that given
func (o *SearchAuditRateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the search audit rate default response
func (o *SearchAuditRateDefault) Code() int {
	return o._statusCode
}

func (o *SearchAuditRateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/audit/forms/{form_id}/rate][%d] SearchAuditRate default %s", o._statusCode, payload)
}

func (o *SearchAuditRateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /call_center/audit/forms/{form_id}/rate][%d] SearchAuditRate default %s", o._statusCode, payload)
}

func (o *SearchAuditRateDefault) GetPayload() *models.EngineAPIError {
	return o.Payload
}

func (o *SearchAuditRateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EngineAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
