// Code generated by go-swagger; DO NOT EDIT.

package agent_absence_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// AgentAbsenceServiceDeleteAgentAbsenceReader is a Reader for the AgentAbsenceServiceDeleteAgentAbsence structure.
type AgentAbsenceServiceDeleteAgentAbsenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentAbsenceServiceDeleteAgentAbsenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAgentAbsenceServiceDeleteAgentAbsenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAgentAbsenceServiceDeleteAgentAbsenceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAgentAbsenceServiceDeleteAgentAbsenceOK creates a AgentAbsenceServiceDeleteAgentAbsenceOK with default headers values
func NewAgentAbsenceServiceDeleteAgentAbsenceOK() *AgentAbsenceServiceDeleteAgentAbsenceOK {
	return &AgentAbsenceServiceDeleteAgentAbsenceOK{}
}

/*
AgentAbsenceServiceDeleteAgentAbsenceOK describes a response with status code 200, with default header values.

A successful response.
*/
type AgentAbsenceServiceDeleteAgentAbsenceOK struct {
	Payload *models.WfmDeleteAgentAbsenceResponse
}

// IsSuccess returns true when this agent absence service delete agent absence Ok response has a 2xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this agent absence service delete agent absence Ok response has a 3xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this agent absence service delete agent absence Ok response has a 4xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this agent absence service delete agent absence Ok response has a 5xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this agent absence service delete agent absence Ok response a status code equal to that given
func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the agent absence service delete agent absence Ok response
func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) Code() int {
	return 200
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /wfm/agents/{agent_id}/absences/{id}][%d] agentAbsenceServiceDeleteAgentAbsenceOk %s", 200, payload)
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /wfm/agents/{agent_id}/absences/{id}][%d] agentAbsenceServiceDeleteAgentAbsenceOk %s", 200, payload)
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) GetPayload() *models.WfmDeleteAgentAbsenceResponse {
	return o.Payload
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WfmDeleteAgentAbsenceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAgentAbsenceServiceDeleteAgentAbsenceDefault creates a AgentAbsenceServiceDeleteAgentAbsenceDefault with default headers values
func NewAgentAbsenceServiceDeleteAgentAbsenceDefault(code int) *AgentAbsenceServiceDeleteAgentAbsenceDefault {
	return &AgentAbsenceServiceDeleteAgentAbsenceDefault{
		_statusCode: code,
	}
}

/*
AgentAbsenceServiceDeleteAgentAbsenceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AgentAbsenceServiceDeleteAgentAbsenceDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this agent absence service delete agent absence default response has a 2xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this agent absence service delete agent absence default response has a 3xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this agent absence service delete agent absence default response has a 4xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this agent absence service delete agent absence default response has a 5xx status code
func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this agent absence service delete agent absence default response a status code equal to that given
func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the agent absence service delete agent absence default response
func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) Code() int {
	return o._statusCode
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /wfm/agents/{agent_id}/absences/{id}][%d] AgentAbsenceService_DeleteAgentAbsence default %s", o._statusCode, payload)
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /wfm/agents/{agent_id}/absences/{id}][%d] AgentAbsenceService_DeleteAgentAbsence default %s", o._statusCode, payload)
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *AgentAbsenceServiceDeleteAgentAbsenceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
