// Code generated by go-swagger; DO NOT EDIT.

package cases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// NewUpdateCaseParams creates a new UpdateCaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateCaseParams() *UpdateCaseParams {
	return &UpdateCaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCaseParamsWithTimeout creates a new UpdateCaseParams object
// with the ability to set a timeout on a request.
func NewUpdateCaseParamsWithTimeout(timeout time.Duration) *UpdateCaseParams {
	return &UpdateCaseParams{
		timeout: timeout,
	}
}

// NewUpdateCaseParamsWithContext creates a new UpdateCaseParams object
// with the ability to set a context for a request.
func NewUpdateCaseParamsWithContext(ctx context.Context) *UpdateCaseParams {
	return &UpdateCaseParams{
		Context: ctx,
	}
}

// NewUpdateCaseParamsWithHTTPClient creates a new UpdateCaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateCaseParamsWithHTTPClient(client *http.Client) *UpdateCaseParams {
	return &UpdateCaseParams{
		HTTPClient: client,
	}
}

/*
UpdateCaseParams contains all the parameters to send to the API endpoint

	for the update case operation.

	Typically these are written to a http.Request.
*/
type UpdateCaseParams struct {

	/* Fields.

	   List of fields to include in the response.
	*/
	Fields []string

	/* Input.

	   Input data with updated fields.
	*/
	Input *models.UpdateCaseParamsBody

	// InputEtag.
	InputEtag string

	/* XJSONMask.

	   List of JSON fields to update.
	*/
	XJSONMask []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update case params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCaseParams) WithDefaults() *UpdateCaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update case params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update case params
func (o *UpdateCaseParams) WithTimeout(timeout time.Duration) *UpdateCaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update case params
func (o *UpdateCaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update case params
func (o *UpdateCaseParams) WithContext(ctx context.Context) *UpdateCaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update case params
func (o *UpdateCaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update case params
func (o *UpdateCaseParams) WithHTTPClient(client *http.Client) *UpdateCaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update case params
func (o *UpdateCaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the update case params
func (o *UpdateCaseParams) WithFields(fields []string) *UpdateCaseParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the update case params
func (o *UpdateCaseParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithInput adds the input to the update case params
func (o *UpdateCaseParams) WithInput(input *models.UpdateCaseParamsBody) *UpdateCaseParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the update case params
func (o *UpdateCaseParams) SetInput(input *models.UpdateCaseParamsBody) {
	o.Input = input
}

// WithInputEtag adds the inputEtag to the update case params
func (o *UpdateCaseParams) WithInputEtag(inputEtag string) *UpdateCaseParams {
	o.SetInputEtag(inputEtag)
	return o
}

// SetInputEtag adds the inputEtag to the update case params
func (o *UpdateCaseParams) SetInputEtag(inputEtag string) {
	o.InputEtag = inputEtag
}

// WithXJSONMask adds the xJSONMask to the update case params
func (o *UpdateCaseParams) WithXJSONMask(xJSONMask []string) *UpdateCaseParams {
	o.SetXJSONMask(xJSONMask)
	return o
}

// SetXJSONMask adds the xJsonMask to the update case params
func (o *UpdateCaseParams) SetXJSONMask(xJSONMask []string) {
	o.XJSONMask = xJSONMask
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// binding items for fields
		joinedFields := o.bindParamFields(reg)

		// query array param fields
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	// path param input.etag
	if err := r.SetPathParam("input.etag", o.InputEtag); err != nil {
		return err
	}

	if o.XJSONMask != nil {

		// binding items for x_json_mask
		joinedXJSONMask := o.bindParamXJSONMask(reg)

		// query array param x_json_mask
		if err := r.SetQueryParam("x_json_mask", joinedXJSONMask...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamUpdateCase binds the parameter fields
func (o *UpdateCaseParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR { // explode []string

		fieldsIIV := fieldsIIR // string as string
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	// items.CollectionFormat: "multi"
	fieldsIS := swag.JoinByFormat(fieldsIC, "multi")

	return fieldsIS
}

// bindParamUpdateCase binds the parameter x_json_mask
func (o *UpdateCaseParams) bindParamXJSONMask(formats strfmt.Registry) []string {
	xJSONMaskIR := o.XJSONMask

	var xJSONMaskIC []string
	for _, xJSONMaskIIR := range xJSONMaskIR { // explode []string

		xJSONMaskIIV := xJSONMaskIIR // string as string
		xJSONMaskIC = append(xJSONMaskIC, xJSONMaskIIV)
	}

	// items.CollectionFormat: "multi"
	xJSONMaskIS := swag.JoinByFormat(xJSONMaskIC, "multi")

	return xJSONMaskIS
}
