// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APILDAProcessOptions api l d a process options
//
// swagger:model api.LDAProcessOptions
type APILDAProcessOptions struct {

	// Allows to create links
	// with fetched LDAP entries
	// for manually created objects
	LinkExistingObjects bool `json:"link_existing_objects,omitempty"`

	// Allows to reassign device's owner user
	// due to preconfigured mapping LDAP template
	ReassignDeviceUsers bool `json:"reassign_device_users,omitempty"`

	// Will NOT perform any operations on storage.
	// To review potential processing only
	Test bool `json:"test,omitempty"`

	// Operation timeout. Not implemented yet
	Timeout string `json:"timeout,omitempty"`
}

// Validate validates this api l d a process options
func (m *APILDAProcessOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api l d a process options based on context it is used
func (m *APILDAProcessOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APILDAProcessOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APILDAProcessOptions) UnmarshalBinary(b []byte) error {
	var res APILDAProcessOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
