// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CasesCreateInputRelatedCase Input for creating a related case.
//
// swagger:model casesCreateInputRelatedCase
type CasesCreateInputRelatedCase struct {

	// Related case details.
	RelatedCase *GeneralLookup `json:"related_case,omitempty"`

	// Relation type between the cases.
	RelationType *CasesRelationType `json:"relation_type,omitempty"`
}

// Validate validates this cases create input related case
func (m *CasesCreateInputRelatedCase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRelatedCase(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelationType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CasesCreateInputRelatedCase) validateRelatedCase(formats strfmt.Registry) error {
	if swag.IsZero(m.RelatedCase) { // not required
		return nil
	}

	if m.RelatedCase != nil {
		if err := m.RelatedCase.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("related_case")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("related_case")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCreateInputRelatedCase) validateRelationType(formats strfmt.Registry) error {
	if swag.IsZero(m.RelationType) { // not required
		return nil
	}

	if m.RelationType != nil {
		if err := m.RelationType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("relation_type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("relation_type")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this cases create input related case based on the context it is used
func (m *CasesCreateInputRelatedCase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRelatedCase(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRelationType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CasesCreateInputRelatedCase) contextValidateRelatedCase(ctx context.Context, formats strfmt.Registry) error {

	if m.RelatedCase != nil {

		if swag.IsZero(m.RelatedCase) { // not required
			return nil
		}

		if err := m.RelatedCase.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("related_case")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("related_case")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCreateInputRelatedCase) contextValidateRelationType(ctx context.Context, formats strfmt.Registry) error {

	if m.RelationType != nil {

		if swag.IsZero(m.RelationType) { // not required
			return nil
		}

		if err := m.RelationType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("relation_type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("relation_type")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CasesCreateInputRelatedCase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CasesCreateInputRelatedCase) UnmarshalBinary(b []byte) error {
	var res CasesCreateInputRelatedCase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
