// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CasesLocateSLAConditionResponse LocateSLAConditionResponse message contains a single SLACondition entity
//
// swagger:model casesLocateSLAConditionResponse
type CasesLocateSLAConditionResponse struct {

	// sla condition
	SLACondition *CasesSLACondition `json:"sla_condition,omitempty"`
}

// Validate validates this cases locate SLA condition response
func (m *CasesLocateSLAConditionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSLACondition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CasesLocateSLAConditionResponse) validateSLACondition(formats strfmt.Registry) error {
	if swag.IsZero(m.SLACondition) { // not required
		return nil
	}

	if m.SLACondition != nil {
		if err := m.SLACondition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sla_condition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sla_condition")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this cases locate SLA condition response based on the context it is used
func (m *CasesLocateSLAConditionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSLACondition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CasesLocateSLAConditionResponse) contextValidateSLACondition(ctx context.Context, formats strfmt.Registry) error {

	if m.SLACondition != nil {

		if swag.IsZero(m.SLACondition) { // not required
			return nil
		}

		if err := m.SLACondition.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sla_condition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sla_condition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CasesLocateSLAConditionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CasesLocateSLAConditionResponse) UnmarshalBinary(b []byte) error {
	var res CasesLocateSLAConditionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
