// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CasesCallFile cases call file
//
// swagger:model casesCallFile
type CasesCallFile struct {

	// id
	ID string `json:"id,omitempty"`

	// mime type
	MimeType string `json:"mime_type,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// size
	Size string `json:"size,omitempty"`

	// start at
	StartAt string `json:"start_at,omitempty"`

	// stop at
	StopAt string `json:"stop_at,omitempty"`
}

// Validate validates this cases call file
func (m *CasesCallFile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cases call file based on context it is used
func (m *CasesCallFile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CasesCallFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CasesCallFile) UnmarshalBinary(b []byte) error {
	var res CasesCallFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
