// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CasesCase Message representing a case.
//
// swagger:model casesCase
type CasesCase struct {

	// Assignee responsible for resolving the case.
	Assignee *GeneralLookup `json:"assignee,omitempty"`

	// Author or reporter of the case.
	Author *GeneralLookup `json:"author,omitempty"`

	// Close information (if applicable).
	Close *CasesCloseInfo `json:"close,omitempty"`

	// Close reason group, immutable once set.
	CloseReasonGroup *GeneralLookup `json:"close_reason_group,omitempty"`

	// List of comments on the case.
	Comments *CasesCaseCommentList `json:"comments,omitempty"`

	// Contact information for the case.
	ContactInfo string `json:"contact_info,omitempty"`

	// Creation timestamp (in milliseconds since Unix epoch).
	CreatedAt string `json:"created_at,omitempty"`

	// Creator of the case.
	CreatedBy *GeneralLookup `json:"created_by,omitempty"`

	// Detailed description of the case.
	Description string `json:"description,omitempty"`

	// Unique etag identifier.
	Etag string `json:"etag,omitempty"`

	// List of attached files.
	Files *CasesCaseFileList `json:"files,omitempty"`

	// Group associated with the case.
	Group *GeneralExtendedLookup `json:"group,omitempty"`

	// Unique case ID.
	ID string `json:"id,omitempty"`

	// Impacted contact (defaults to reporter if null).
	Impacted *GeneralLookup `json:"impacted,omitempty"`

	// List of attached links.
	Links *CasesCaseLinkList `json:"links,omitempty"`

	// Name of the case (may serve as an ID in docs).
	Name string `json:"name,omitempty"`

	// Planned reaction time (in milliseconds).
	PlannedReactionAt string `json:"planned_reaction_at,omitempty"`

	// Planned resolution time (in milliseconds).
	PlannedResolveAt string `json:"planned_resolve_at,omitempty"`

	// Priority level of the case.
	Priority *CasesPriority `json:"priority,omitempty"`

	// Rating information.
	Rate *CasesRateInfo `json:"rate,omitempty"`

	// List of related cases.
	Related *CasesRelatedCaseList `json:"related,omitempty"`

	// Reporter of the issue (null if anonymous).
	Reporter *GeneralLookup `json:"reporter,omitempty"`

	// Service associated with the case.
	Service *GeneralLookup `json:"service,omitempty"`

	// SLA associated with the case.
	SLA *GeneralLookup `json:"sla,omitempty"`

	// List of SLA conditions.
	SLACondition *GeneralLookup `json:"sla_condition,omitempty"`

	// Source of the case.
	Source *CasesSourceTypeLookup `json:"source,omitempty"`

	// Current status of the case.
	Status *GeneralLookup `json:"status,omitempty"`

	// Status condition from status lookup.
	StatusCondition *CasesStatusCondition `json:"status_condition,omitempty"`

	// Subject of the case.
	Subject string `json:"subject,omitempty"`

	// SLA timing details.
	Timing *CasesTimingInfo `json:"timing,omitempty"`

	// Last update timestamp (in milliseconds since Unix epoch).
	UpdatedAt string `json:"updated_at,omitempty"`

	// Last updater of the case.
	UpdatedBy *GeneralLookup `json:"updated_by,omitempty"`

	// Version number of the case.
	Ver int32 `json:"ver,omitempty"`
}

// Validate validates this cases case
func (m *CasesCase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssignee(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClose(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloseReasonGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateComments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFiles(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImpacted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriority(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReporter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSLA(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSLACondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatusCondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTiming(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedBy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CasesCase) validateAssignee(formats strfmt.Registry) error {
	if swag.IsZero(m.Assignee) { // not required
		return nil
	}

	if m.Assignee != nil {
		if err := m.Assignee.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assignee")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("assignee")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateAuthor(formats strfmt.Registry) error {
	if swag.IsZero(m.Author) { // not required
		return nil
	}

	if m.Author != nil {
		if err := m.Author.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("author")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("author")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateClose(formats strfmt.Registry) error {
	if swag.IsZero(m.Close) { // not required
		return nil
	}

	if m.Close != nil {
		if err := m.Close.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("close")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("close")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateCloseReasonGroup(formats strfmt.Registry) error {
	if swag.IsZero(m.CloseReasonGroup) { // not required
		return nil
	}

	if m.CloseReasonGroup != nil {
		if err := m.CloseReasonGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("close_reason_group")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("close_reason_group")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateComments(formats strfmt.Registry) error {
	if swag.IsZero(m.Comments) { // not required
		return nil
	}

	if m.Comments != nil {
		if err := m.Comments.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("comments")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("comments")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateCreatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedBy) { // not required
		return nil
	}

	if m.CreatedBy != nil {
		if err := m.CreatedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("created_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("created_by")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateFiles(formats strfmt.Registry) error {
	if swag.IsZero(m.Files) { // not required
		return nil
	}

	if m.Files != nil {
		if err := m.Files.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("files")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("files")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateGroup(formats strfmt.Registry) error {
	if swag.IsZero(m.Group) { // not required
		return nil
	}

	if m.Group != nil {
		if err := m.Group.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("group")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("group")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateImpacted(formats strfmt.Registry) error {
	if swag.IsZero(m.Impacted) { // not required
		return nil
	}

	if m.Impacted != nil {
		if err := m.Impacted.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("impacted")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("impacted")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validatePriority(formats strfmt.Registry) error {
	if swag.IsZero(m.Priority) { // not required
		return nil
	}

	if m.Priority != nil {
		if err := m.Priority.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("priority")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("priority")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateRate(formats strfmt.Registry) error {
	if swag.IsZero(m.Rate) { // not required
		return nil
	}

	if m.Rate != nil {
		if err := m.Rate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rate")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateRelated(formats strfmt.Registry) error {
	if swag.IsZero(m.Related) { // not required
		return nil
	}

	if m.Related != nil {
		if err := m.Related.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("related")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("related")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateReporter(formats strfmt.Registry) error {
	if swag.IsZero(m.Reporter) { // not required
		return nil
	}

	if m.Reporter != nil {
		if err := m.Reporter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reporter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reporter")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateService(formats strfmt.Registry) error {
	if swag.IsZero(m.Service) { // not required
		return nil
	}

	if m.Service != nil {
		if err := m.Service.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("service")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("service")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateSLA(formats strfmt.Registry) error {
	if swag.IsZero(m.SLA) { // not required
		return nil
	}

	if m.SLA != nil {
		if err := m.SLA.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sla")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sla")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateSLACondition(formats strfmt.Registry) error {
	if swag.IsZero(m.SLACondition) { // not required
		return nil
	}

	if m.SLACondition != nil {
		if err := m.SLACondition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sla_condition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sla_condition")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateSource(formats strfmt.Registry) error {
	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateStatusCondition(formats strfmt.Registry) error {
	if swag.IsZero(m.StatusCondition) { // not required
		return nil
	}

	if m.StatusCondition != nil {
		if err := m.StatusCondition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status_condition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status_condition")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateTiming(formats strfmt.Registry) error {
	if swag.IsZero(m.Timing) { // not required
		return nil
	}

	if m.Timing != nil {
		if err := m.Timing.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("timing")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("timing")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) validateUpdatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedBy) { // not required
		return nil
	}

	if m.UpdatedBy != nil {
		if err := m.UpdatedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updated_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updated_by")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this cases case based on the context it is used
func (m *CasesCase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAssignee(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAuthor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateClose(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCloseReasonGroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateComments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFiles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImpacted(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePriority(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRelated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReporter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateService(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSLA(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSLACondition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatusCondition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTiming(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CasesCase) contextValidateAssignee(ctx context.Context, formats strfmt.Registry) error {

	if m.Assignee != nil {

		if swag.IsZero(m.Assignee) { // not required
			return nil
		}

		if err := m.Assignee.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assignee")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("assignee")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateAuthor(ctx context.Context, formats strfmt.Registry) error {

	if m.Author != nil {

		if swag.IsZero(m.Author) { // not required
			return nil
		}

		if err := m.Author.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("author")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("author")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateClose(ctx context.Context, formats strfmt.Registry) error {

	if m.Close != nil {

		if swag.IsZero(m.Close) { // not required
			return nil
		}

		if err := m.Close.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("close")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("close")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateCloseReasonGroup(ctx context.Context, formats strfmt.Registry) error {

	if m.CloseReasonGroup != nil {

		if swag.IsZero(m.CloseReasonGroup) { // not required
			return nil
		}

		if err := m.CloseReasonGroup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("close_reason_group")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("close_reason_group")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateComments(ctx context.Context, formats strfmt.Registry) error {

	if m.Comments != nil {

		if swag.IsZero(m.Comments) { // not required
			return nil
		}

		if err := m.Comments.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("comments")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("comments")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateCreatedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedBy != nil {

		if swag.IsZero(m.CreatedBy) { // not required
			return nil
		}

		if err := m.CreatedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("created_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("created_by")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateFiles(ctx context.Context, formats strfmt.Registry) error {

	if m.Files != nil {

		if swag.IsZero(m.Files) { // not required
			return nil
		}

		if err := m.Files.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("files")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("files")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateGroup(ctx context.Context, formats strfmt.Registry) error {

	if m.Group != nil {

		if swag.IsZero(m.Group) { // not required
			return nil
		}

		if err := m.Group.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("group")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("group")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateImpacted(ctx context.Context, formats strfmt.Registry) error {

	if m.Impacted != nil {

		if swag.IsZero(m.Impacted) { // not required
			return nil
		}

		if err := m.Impacted.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("impacted")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("impacted")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if m.Links != nil {

		if swag.IsZero(m.Links) { // not required
			return nil
		}

		if err := m.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidatePriority(ctx context.Context, formats strfmt.Registry) error {

	if m.Priority != nil {

		if swag.IsZero(m.Priority) { // not required
			return nil
		}

		if err := m.Priority.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("priority")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("priority")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateRate(ctx context.Context, formats strfmt.Registry) error {

	if m.Rate != nil {

		if swag.IsZero(m.Rate) { // not required
			return nil
		}

		if err := m.Rate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("rate")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateRelated(ctx context.Context, formats strfmt.Registry) error {

	if m.Related != nil {

		if swag.IsZero(m.Related) { // not required
			return nil
		}

		if err := m.Related.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("related")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("related")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateReporter(ctx context.Context, formats strfmt.Registry) error {

	if m.Reporter != nil {

		if swag.IsZero(m.Reporter) { // not required
			return nil
		}

		if err := m.Reporter.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("reporter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("reporter")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateService(ctx context.Context, formats strfmt.Registry) error {

	if m.Service != nil {

		if swag.IsZero(m.Service) { // not required
			return nil
		}

		if err := m.Service.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("service")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("service")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateSLA(ctx context.Context, formats strfmt.Registry) error {

	if m.SLA != nil {

		if swag.IsZero(m.SLA) { // not required
			return nil
		}

		if err := m.SLA.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sla")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sla")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateSLACondition(ctx context.Context, formats strfmt.Registry) error {

	if m.SLACondition != nil {

		if swag.IsZero(m.SLACondition) { // not required
			return nil
		}

		if err := m.SLACondition.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sla_condition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sla_condition")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateSource(ctx context.Context, formats strfmt.Registry) error {

	if m.Source != nil {

		if swag.IsZero(m.Source) { // not required
			return nil
		}

		if err := m.Source.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {

		if swag.IsZero(m.Status) { // not required
			return nil
		}

		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateStatusCondition(ctx context.Context, formats strfmt.Registry) error {

	if m.StatusCondition != nil {

		if swag.IsZero(m.StatusCondition) { // not required
			return nil
		}

		if err := m.StatusCondition.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status_condition")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status_condition")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateTiming(ctx context.Context, formats strfmt.Registry) error {

	if m.Timing != nil {

		if swag.IsZero(m.Timing) { // not required
			return nil
		}

		if err := m.Timing.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("timing")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("timing")
			}
			return err
		}
	}

	return nil
}

func (m *CasesCase) contextValidateUpdatedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.UpdatedBy != nil {

		if swag.IsZero(m.UpdatedBy) { // not required
			return nil
		}

		if err := m.UpdatedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updated_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updated_by")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CasesCase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CasesCase) UnmarshalBinary(b []byte) error {
	var res CasesCase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
