// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineCreateSkillAgentRequest engine create skill agent request
//
// swagger:model engineCreateSkillAgentRequest
type EngineCreateSkillAgentRequest struct {

	// agent
	Agent []*EngineLookup `json:"agent"`

	// capacity
	Capacity int32 `json:"capacity,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// skill id
	SkillID string `json:"skill_id,omitempty"`
}

// Validate validates this engine create skill agent request
func (m *EngineCreateSkillAgentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAgent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EngineCreateSkillAgentRequest) validateAgent(formats strfmt.Registry) error {
	if swag.IsZero(m.Agent) { // not required
		return nil
	}

	for i := 0; i < len(m.Agent); i++ {
		if swag.IsZero(m.Agent[i]) { // not required
			continue
		}

		if m.Agent[i] != nil {
			if err := m.Agent[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("agent" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("agent" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this engine create skill agent request based on the context it is used
func (m *EngineCreateSkillAgentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAgent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EngineCreateSkillAgentRequest) contextValidateAgent(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Agent); i++ {

		if m.Agent[i] != nil {

			if swag.IsZero(m.Agent[i]) { // not required
				return nil
			}

			if err := m.Agent[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("agent" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("agent" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EngineCreateSkillAgentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineCreateSkillAgentRequest) UnmarshalBinary(b []byte) error {
	var res EngineCreateSkillAgentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
