// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EngineBroadcastFile Media File.
//
// swagger:model engineBroadcastFile
type EngineBroadcastFile struct {

	// id
	ID string `json:"id,omitempty"`

	// mime
	Mime string `json:"mime,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// size
	Size string `json:"size,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this engine broadcast file
func (m *EngineBroadcastFile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this engine broadcast file based on context it is used
func (m *EngineBroadcastFile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EngineBroadcastFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EngineBroadcastFile) UnmarshalBinary(b []byte) error {
	var res EngineBroadcastFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
