// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoggerDeleteConfigLogsRequest logger delete config logs request
//
// swagger:model loggerDeleteConfigLogsRequest
type LoggerDeleteConfigLogsRequest struct {

	// Required
	ConfigID string `json:"config_id,omitempty"`

	// Not required
	OlderThan string `json:"older_than,omitempty"`
}

// Validate validates this logger delete config logs request
func (m *LoggerDeleteConfigLogsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this logger delete config logs request based on context it is used
func (m *LoggerDeleteConfigLogsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoggerDeleteConfigLogsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoggerDeleteConfigLogsRequest) UnmarshalBinary(b []byte) error {
	var res LoggerDeleteConfigLogsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
