// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SpacesUpdateSpaceParamsBody NEW Space source changes
//
// swagger:model spacesUpdateSpaceParamsBody
type SpacesUpdateSpaceParamsBody struct {

	// BIO. Short description about the space.
	// OPTIONAL. Multi-lined text.
	HomePage string `json:"home_page,omitempty"`

	// Represents the name of the knowledge base space.
	Name string `json:"name,omitempty"`

	// The state of the space.
	State bool `json:"state,omitempty"`
}

// Validate validates this spaces update space params body
func (m *SpacesUpdateSpaceParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this spaces update space params body based on context it is used
func (m *SpacesUpdateSpaceParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SpacesUpdateSpaceParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SpacesUpdateSpaceParamsBody) UnmarshalBinary(b []byte) error {
	var res SpacesUpdateSpaceParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
