// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageThumbnail storage thumbnail
//
// swagger:model storageThumbnail
type StorageThumbnail struct {

	// mime type
	MimeType string `json:"mime_type,omitempty"`

	// scale
	Scale string `json:"scale,omitempty"`

	// size
	Size string `json:"size,omitempty"`
}

// Validate validates this storage thumbnail
func (m *StorageThumbnail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage thumbnail based on context it is used
func (m *StorageThumbnail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageThumbnail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageThumbnail) UnmarshalBinary(b []byte) error {
	var res StorageThumbnail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
