// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageFile storage file
//
// swagger:model storageFile
type StorageFile struct {

	// channel
	Channel *StorageUploadFileChannel `json:"channel,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// mime type
	MimeType string `json:"mime_type,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// reference id
	ReferenceID string `json:"reference_id,omitempty"`

	// retention until
	RetentionUntil string `json:"retention_until,omitempty"`

	// sha256sum
	Sha256sum string `json:"sha256sum,omitempty"`

	// size
	Size string `json:"size,omitempty"`

	// thumbnail
	Thumbnail *StorageThumbnail `json:"thumbnail,omitempty"`

	// uploaded at
	UploadedAt string `json:"uploaded_at,omitempty"`

	// uploaded by
	UploadedBy *EngineLookup `json:"uploaded_by,omitempty"`

	// uuid
	UUID string `json:"uuid,omitempty"`

	// view name
	ViewName string `json:"view_name,omitempty"`
}

// Validate validates this storage file
func (m *StorageFile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChannel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThumbnail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUploadedBy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageFile) validateChannel(formats strfmt.Registry) error {
	if swag.IsZero(m.Channel) { // not required
		return nil
	}

	if m.Channel != nil {
		if err := m.Channel.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("channel")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("channel")
			}
			return err
		}
	}

	return nil
}

func (m *StorageFile) validateThumbnail(formats strfmt.Registry) error {
	if swag.IsZero(m.Thumbnail) { // not required
		return nil
	}

	if m.Thumbnail != nil {
		if err := m.Thumbnail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thumbnail")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("thumbnail")
			}
			return err
		}
	}

	return nil
}

func (m *StorageFile) validateUploadedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.UploadedBy) { // not required
		return nil
	}

	if m.UploadedBy != nil {
		if err := m.UploadedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("uploaded_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("uploaded_by")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this storage file based on the context it is used
func (m *StorageFile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChannel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateThumbnail(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUploadedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageFile) contextValidateChannel(ctx context.Context, formats strfmt.Registry) error {

	if m.Channel != nil {

		if swag.IsZero(m.Channel) { // not required
			return nil
		}

		if err := m.Channel.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("channel")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("channel")
			}
			return err
		}
	}

	return nil
}

func (m *StorageFile) contextValidateThumbnail(ctx context.Context, formats strfmt.Registry) error {

	if m.Thumbnail != nil {

		if swag.IsZero(m.Thumbnail) { // not required
			return nil
		}

		if err := m.Thumbnail.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thumbnail")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("thumbnail")
			}
			return err
		}
	}

	return nil
}

func (m *StorageFile) contextValidateUploadedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.UploadedBy != nil {

		if swag.IsZero(m.UploadedBy) { // not required
			return nil
		}

		if err := m.UploadedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("uploaded_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("uploaded_by")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageFile) UnmarshalBinary(b []byte) error {
	var res StorageFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
