// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateLinkParamsBody update link params body
//
// swagger:model updateLinkParamsBody
type UpdateLinkParamsBody struct {

	// name
	Name string `json:"name,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this update link params body
func (m *UpdateLinkParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update link params body based on context it is used
func (m *UpdateLinkParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateLinkParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateLinkParamsBody) UnmarshalBinary(b []byte) error {
	var res UpdateLinkParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
