// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserAccessTokensAddUserAccessTokenParamsBodyUser [optional] output depends on API endpoint
//
// swagger:model userAccessTokensAddUserAccessTokenParamsBodyUser
type UserAccessTokensAddUserAccessTokenParamsBodyUser struct {

	// display name
	Name string `json:"name,omitempty"`
}

// Validate validates this user access tokens add user access token params body user
func (m *UserAccessTokensAddUserAccessTokenParamsBodyUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user access tokens add user access token params body user based on context it is used
func (m *UserAccessTokensAddUserAccessTokenParamsBodyUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserAccessTokensAddUserAccessTokenParamsBodyUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserAccessTokensAddUserAccessTokenParamsBodyUser) UnmarshalBinary(b []byte) error {
	var res UserAccessTokensAddUserAccessTokenParamsBodyUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
