// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebitelChatInputButton webitel chat input button
//
// swagger:model webitel.chat.InputButton
type WebitelChatInputButton struct {

	// caption
	Caption string `json:"caption,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this webitel chat input button
func (m *WebitelChatInputButton) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this webitel chat input button based on context it is used
func (m *WebitelChatInputButton) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebitelChatInputButton) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebitelChatInputButton) UnmarshalBinary(b []byte) error {
	var res WebitelChatInputButton
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
