// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebitelChatPeer Peer contact.
//
// swagger:model webitel.chat.Peer
type WebitelChatPeer struct {

	// Contact unique **ID**entifier.
	// Contact **type**-specific string.
	ID string `json:"id,omitempty"`

	// Contact display **name**.
	Name string `json:"name,omitempty"`

	// Contact **type** provider.
	Type string `json:"type,omitempty"`
}

// Validate validates this webitel chat peer
func (m *WebitelChatPeer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this webitel chat peer based on context it is used
func (m *WebitelChatPeer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebitelChatPeer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebitelChatPeer) UnmarshalBinary(b []byte) error {
	var res WebitelChatPeer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
