// Code generated by go-swagger; DO NOT EDIT.

package labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/webitel/webitel-openapi-client-go/models"
)

// LabelsGetLabelsReader is a Reader for the LabelsGetLabels structure.
type LabelsGetLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LabelsGetLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLabelsGetLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /contacts/labels] Labels_GetLabels", response, response.Code())
	}
}

// NewLabelsGetLabelsOK creates a LabelsGetLabelsOK with default headers values
func NewLabelsGetLabelsOK() *LabelsGetLabelsOK {
	return &LabelsGetLabelsOK{}
}

/*
LabelsGetLabelsOK describes a response with status code 200, with default header values.

A successful response.
*/
type LabelsGetLabelsOK struct {
	Payload *models.WebitelContactsLabelTags
}

// IsSuccess returns true when this labels get labels Ok response has a 2xx status code
func (o *LabelsGetLabelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this labels get labels Ok response has a 3xx status code
func (o *LabelsGetLabelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this labels get labels Ok response has a 4xx status code
func (o *LabelsGetLabelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this labels get labels Ok response has a 5xx status code
func (o *LabelsGetLabelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this labels get labels Ok response a status code equal to that given
func (o *LabelsGetLabelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the labels get labels Ok response
func (o *LabelsGetLabelsOK) Code() int {
	return 200
}

func (o *LabelsGetLabelsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contacts/labels][%d] labelsGetLabelsOk %s", 200, payload)
}

func (o *LabelsGetLabelsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contacts/labels][%d] labelsGetLabelsOk %s", 200, payload)
}

func (o *LabelsGetLabelsOK) GetPayload() *models.WebitelContactsLabelTags {
	return o.Payload
}

func (o *LabelsGetLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebitelContactsLabelTags)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
